<!--<div class="full search-outer">
    <div class="search-wrapper">
      <div id="search-box">
        <div id="search-head"><h2 class="white">Search Anything for your Wedding</h2></div>
        <div id="frm-elements">
       		<input name="categoryfield" id="categoryfield" type="text" class="input-txt box1 fl-lt" value="" placeholder="e.g. Banquet, Jeweller etc."  onkeypress="gotolocation(event)" onclick="removeeror()"/>
            
            <div class="in-txt fl-lt">in</div>
             <input name="locationfield" id="locationfield" type="text" class="input-txt box3 fl-lt" value="" placeholder="e.g. Karol bagh etc."  onKeyPress="gosearch(event)"  />
          
            <div class="fl-lt search-btn">
             <a id="search" name="search" class="btn-go" onclick="gosearch('<?php echo"search"; ?>')"><img src="<?=WEBSITE_Image?>/spacer.gif" alt="Spacer Image" /></a>
            </div>
     
        </div>
      </div>
    </div>
  </div>-->
<div id="wrapper-inside">
<div id="content-in">
    <!--<div id="breadcrumbs-cont"> <a href="#">Home</a> &rsaquo; <a href="#">Category Name</a> &rsaquo; Result Name </div>-->
    <!-- breadcrumbs-cont Ends -->
    <div class="fl-lt full pad-bott"> 
		<div class="fl-lt pos-rel">
        	<img src="<?php echo WEBSITE_Image?>/404-img.jpg" alt="404 Error" />
        	<div class="error-cont fl-rt" style="margin-right:-10px;">
                <h1 class="fl-lt" style="font-size:30px; margin-bottom:30px; line-height:42px; color:#fff;">The page you are Looking for is not available but I Am!</h1>
                <span class="fl-lt full txt">Not interested, try the links below:</span>
                <div class="fl-lt mar marg-top4 pad-lt" style="padding-right:29px;"><a href="<?=WEBSITE_URL?>"><img src="<?=WEBSITE_Image?>/home-lnk.png" alt="Home" /></a></div>
                <div class="fl-lt marg-top4 pad-rt"><a href="<?=WEBSITE_URL?>wedding-planning-tools"><img src="<?=WEBSITE_Image?>/plan-lnk.png" alt="Wedding Planning" /></a></div>
                <div class="fl-lt marg-top4"><a href="<?=WEBSITE_URL?>wedding-website"><img src="<?=WEBSITE_Image?>/website-lnk.png" alt="Wedding Website" /></a></div>
                <span class="fl-rt full txt" style="display:block;padding-top:50px;width:100%;">Or Simply&nbsp; <a href="javascript:history.go(-1);" class="pink-box pad">Go Back</a> &nbsp;</span>
            </div>
             
        </div>
   
     
    </div>
    <!-- content-in Ends -->
</div>