
				<div class="col-lg-9">
				<div class="well">			
				<section class="widget">
				<div class="row">
					<div class="col-sm-2">
					<img src="/images/doctor.jpg" alt="">
					</div>
					<div class="col-sm-8">
					<a href="#"><h5>Dr.Krishna Kumar</h5></a>
					<p>MBBS General Medicine, DM - Neurology </p>
					<p>10 Years Experience Overall</p>
					<p style="background-color:#ddd; width:15%">Allopath</p>
					<br>
					<span class="icon">
					 <i class="fa fa-check-circle" style="color: green;font-size:18px" aria-hidden="true"></i>
					</span>
					 Medical Registration Verified
					 <br>
					<span class="icon" style="color:green; font-size:18px">
					 <i class="fa fa-thumbs-up" aria-hidden="true"></i>
					</span>
					<span style="color:green"><b> 96%</b></span>
					<span>(758 votes)</span>
					<br>
					<span> Dr.krishna Kumar is an extremely brilliant and distinguishing Neurologist 
					in Bangalore, with more than 10 years of experience in him profession, 
					spanning many positions and hospitals across the state. He is awarded with 
					Clinical Fellowship in Cerebrovascular diseases from the University of Calgary, 
					Canada where he has worked for 2 years. He specialises in the treatment of stroke.
					Dr. Krisha Kumar has presented vast number of research papers and publications pertaining to diverse
					concerns in Neurology. Many of him articles have been selected to 
					be presented at both national and International levels.</span>
					<br>
					<button type="submit" class="btn btn" value="submit" style="background-color:fff; color:#05c7f7;border: 1px solid #05c7f7;float:right"><a href="share-experience.php">Share Experience</a></button>
				
					</div>
							
				</div>
				
				</section></div>
						
				
				</div>
				