<!-- [END]Jquery Autocomplete -->
<div class="container-fluid">
    <div class="content-wrap">
        <main id="content" class="content" role="main">
            <div class="row">
                <div class="col-sm-12">
                    <div class="well">
                        <section class="widget" style="background-color:#FFF; margin-top:2rem">


                            <form style="padding:15px" class="form-horizontal" action="<?php echo $this->url(array('action' => 'savelabtestresult'), 'laboratoryRequests', true); ?>" method="POST">
                                <div class="row">
                                    <input type = "hidden" id ="patient_id" name ="patient_id" value = "<?php echo $this->labRequestData['patient_id']; ?>">
                                    <input type = "hidden" id ="registration_no" name ="registration_no" value = "<?php echo $this->labRequestData['registration_no']; ?>">
                                    <input type = "hidden" id ="id" name ="id" value = "<?php echo $this->formdata['id']; ?>">
                                    <input type = "hidden" id ="reqid" name ="reqid" value = "<?php echo $this->labRequestData['id']; ?>">
<!--                                    <input type = "hidden" id ="doctor_id" name ="doctor_id" value = "<?php echo $this->doctor_id; ?>">-->

                                    <fieldset>
                                        <legend><strong>Immunization</strong> form</legend>
                                        <div class="form-group row" style ="text-align: center;">

                                            <div class="col-md-11">

                                                <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                                                <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
                                                    <div class="notification-error">
                                                        <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                            <?php echo $msg; ?>
                                                        <?php } ?>
                                                    </div>
                                                <?php } ?>
                                                <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                                                <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
                                                    <div class="notification-suc">
                                                        <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                            <?php echo $msg; ?>
                                                        <?php } ?>
                                                    </div>
                                                <?php } ?>


                                            </div>
                                        </div>
                                        <div class="col-sm-6">

                                            <div style="background-color:lightblue;">

                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Delivery :</b></label>
                                                    
                                                    <input class="form-control datepicker" type="date"  id="delivery_date" name = "delivery_date"   data-value="[1,6,2014]">
                                                </div>
                                                

                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Neonatal Status:</b></label>
                                                    <input type = "text"  id="neonatal_status:" name="neonatal_status"  required class="form-control input-lg" >

                                                </div>
                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Length :</b></label>
                                                    <input type = "text"  id="length" name="length"  required class="form-control input-lg" >

                                                </div>
                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Birth Weight:</b></label>
                                                    <input type = "text"  id="birth_weight:" name="birth_weight"  required class="form-control input-lg" >

                                                </div>
                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Head Circumference :</b></label>
                                                    <input type = "text"  id="head_circumference:" name="head_circumference"  required class="form-control input-lg" >

                                                </div>
                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Blood Group :</b></label>
                                                    <input type = "text"  id="blood_group" name="blood_group"  required class="form-control input-lg" >

                                                </div>
                                                <div class="form-group">
                                                    <label  for="Consultation"><b>Remarks :</b></label>
                                                    <input type = "text"  id="remarks" name="remarks"  required class="form-control input-lg" >

                                                </div>



                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <br>
                                            <br>
                                            <div>
                                                <table style ="background-color:grey;border:1px solid;text-align: center;">
                                                    <tr>
                                                        <th style="width:8%;">AGE</th>
                                                        <th style="width:20%;">VACCINE</th>
                                                        <th style="width:8%;">DUE ON</th>
                                                        <th style="width:8%;">GIVEN ON</th>
                                                        <th style="width:8%;">WEIGHT</th>
                                                        <th style="width:8%;">HEIGHT</th>
                                                        <th style="width:10%;">BATCH</th>
                                                        <th style="width:10%;">HEAD CIRCUMFERENCE</th>

                                                    </tr>

                                                    <?php
                                                    //print_r($this->imuzData);
                                                    if (!empty($this->imuzData)) {
                                                        $ageArr = array();
                                                        foreach ($this->imuzData as $key => $imuzDataVal) {
                                                            $rowCont = count($imuzDataVal);
                                                            foreach ($imuzDataVal as $k => $imuzVal) {
                                                                $id = $imuzVal['id'];
                                                                if (in_array($key, $ageArr)) {
                                                                    ?>

                                                                    <tr>
                                                                        <td  align="center" style="background-color:white "><?php echo $imuzVal['vaccine_name']; ?></td>
                                                                        <td></td>
                                                                        <td>&nbsp;</td>
                                                                        <td><textarea id="batch_<?php echo $id; ?>" name="batch_<?php echo $id; ?>" rows="1" cols="15"></textarea></td>

                                                                    </tr>

                                                                    <?php
                                                                } else {
                                                                    $ageArr[] = $key;
                                                                    ?>

                                                                    <tr>
                                                                        <td rowspan="<?php echo $rowCont; ?>" align="center"><?php echo $key; ?></td>
                                                                        <td align="center" style="background-color:white "><?php echo $imuzVal['vaccine_name']; ?></td>
                                                                        <td>&nbsp;</td>
                                                                        <td>&nbsp;</td>
                                                                        <td rowspan="<?php echo $rowCont; ?>" align="center"><textarea id="height_<?php echo $id; ?>" name="height_<?php echo $id; ?>" rows="1" cols="5"></textarea></td>
                                                                        <td rowspan="<?php echo $rowCont; ?>" align="center"><textarea id="weight_<?php echo $id; ?>" name="weight_<?php echo $id; ?>" rows="1" cols="5"></textarea></td>
                                                                        <td align="center"><textarea id="batch_<?php echo $id; ?>" name="batch_<?php echo $id; ?>" rows="1" cols="15"></textarea></td>
                                                                        <td rowspan="<?php echo $rowCont; ?>" align="center"><textarea id="Headcir_<?php echo $id; ?>" name="Headcir_<?php echo $id; ?>" rows="1" cols="5"></textarea></td>
                                                                    </tr>

                                                                <?php }
                                                                ?>


                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>




                                                </table>

                                            </div>

                                        </div>




                                    </fieldset>










                                </div>
                                <button type="button" class="btn btn-danger" id = 'button2' onClick = "cancelBack('laboratory/index');">Cancel</button>
                                <span id = "sve_btn">
                                    <button type="submit" style="text-align:right" class="btn btn-primary" id = 'save_button'>Save</button>
                                </span>
                            </form>
                            <div id = "f-l-name"></div>

                        </section>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        line-height:1.5!important;
    }
    th, td {
        padding: 15px;

    }
    table#t01 {
        width: 100%;    
        background-color: #f1f1c1;
    }
</style>