<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <section class="widget">
		 <div class="widget-body">
			
			<div>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.5321182451307!2d77.5781107142427!3d12.937765519121752!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae158e750221f1%3A0xf18e3d80c3d298aa!2sThe%20Bangalore%20Hospital!5e0!3m2!1sen!2sin!4v1572610521647!5m2!1sen!2sin" 
                                width="950" height="500" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
			</div>
       </section>
       </main>
</div>
    </div>

<script language="javascript">


</script>

