<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <section class="widget">
		 <div class="widget-body">
			
			<div>
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d224000.14618444414!2d76.98778573749101!3d28.689578279400088!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sdelhi%20hospital!5e0!3m2!1sen!2sin!4v1572610191984!5m2!1sen!2sin" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe></div>
			</div>
       </section>
       </main>
</div>
    </div>

<script language="javascript">


</script>

