
<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <!-- Page content -->
       <!-- <ol class="breadcrumb">
            <li class="breadcrumb-item">Dashboard</li>
            <li class="breadcrumb-item active">Patient profile</li>
        </ol>-->

        <div class="row">
            <div class="col-md-form">
                <section class="widget">
                    <header>
                       
                        <div class="widget-controls">
                        </div>
                    </header>
                    <div class="widget-body">
                         
                        <iframe src="<?php echo $this->ipfsHashURL;?>" width="800px" height="800px"></iframe> 
                        
                        <div id = "f-l-name"></div>
                    </div>
                </section>
            </div>

        </div>
       </main>
</div>
    </div>

<script type='text/javascript'>

    
    function displayFileName(){
        
        var filename = $('#fileupload1').val();
        //alert(filename);
        $('#fileinput_filename').html(filename);
    }
</script>

