
<?php echo $this->partial('partial/static_header.phtml',array('video'=>1,'section'=>""));?>
<?php echo $this->partial('partial/static_navbar.phtml',array('section'=>""));?>
<!-- \\ End Secondary Navigation -->
<!-- Section About Us -->
<div class="section-about-us">
    <div class="site-width">
        
        <p class="text-center font-27px "><?php echo $this->msg;?></p>
        <p class="text-center font-27px "><a href="<?php echo WEBSITE_URL;?>">Back to Vivahaayojan Home</a></p>
        
    </div>
</div>
