<!--<a href="javascript:void(0);" class="js-modal-close close">×</a>-->
<div class="modal-header forget-head50">
    <h2 class="forget-head"><?php echo $this->frmMsg['FORGOTPASSWORD']; ?> </h2>
</div>
<style>
    .reset-popup{ min-height: 40px;
                  padding: 30px;}
    .forget-head{ margin-top: 1px;
                  padding-bottom: 0;}
    .forgetpad1{padding: 2px 16px 0!important;}
    .forget-head50{ height:47px;}
    @media screen and (-webkit-min-device-pixel-ratio:0) { 
     .forget-head50{ height:40px;}

}

</style>


<div id="forgot_error" class="fl-lt error-tip" style="display: none;"></div>
<div id="forgot_sucess_div">
    <div class="modal-body toppadding">
        <p style="padding:10px 16px 0 16px;">Plz enter your email id below and we will mail you the new password instantly !</p>
        <!--<form action="" class="sky-form">-->
        <?php echo $this->form('forgotpass', array('name' => 'forgotpass', 'id' => 'forgotpass', 'class' => 'sky-form mob-form1', 'method' => 'post', 'action' => "")); ?>    
        <fieldset class="forgetpad1">
            <section>
                <div class="row-pop">
                    <label class="input">
                        <?php echo $this->formText('email', '', array('id' => 'email', 'name' => 'email', 'placeholder' => 'Email')); ?>

                    </label>
                </div>
            </section>
            <section>
                <div style="width:340px; padding-bottom: 20px;">
                    <div class="row mob-form">
                        <!--<a href="#" style="float:left; margin-left: 25px!important;" id="forgotsubmit" onclick="" class="radius-btn mypop">Reset Password</a>-->
                        <a href="javascript:void(0);" onclick="javascript:loginForm();" style="float:left;  margin-left: 25px!important; " class="round-tbm radius-btn-loginpop-text enqury"> <i class="fa fa-angle-left"> &nbsp; &nbsp;</i>Back to login</a>

                        <input id="forgotsubmit" type="submit" style="float:left; margin-left: 25px!important;" class="radius-btn-loginpop-50" value="Reset Password" />

                    </div>
                </div>
            </section>
        </fieldset>
        </form>
    </div>
</div>
<div style="clear:both;"></div>
<style>
    .popupmessage {
        float:left;
        overflow:none;
        padding-bottom:10px;
    }


</style>
<!--Inline Js Specific to the popup-->
<script type="text/javascript">
    $(document).ready(function () {
        $("#forgotpass").validate({
            onkeyup: false,
            errorClass: 'error-tip',
            rules: {
                email: {
                    required: true,
                    minlength: 5,
                    email: true
                }
            },
            messages: {
                email: {
                    required: '<?php echo $this->errMsg['email']['no_empty']; ?>',
                    minlength: '<?php echo $this->errMsg['email']['min_length']; ?>'
                }
            },
            success: function (element) {
                $(element).addClass("checked");
                $(element).parent("label").removeClass("error-tip");
                //$.fn.colorbox.resize({height: "", width: ""});
            },
            errorPlacement: function (error, element) {
                error.insertBefore(element);
                //$.fn.colorbox.resize({height: "", width: ""});
            },
            //debug:true,
            highlight: function (element, errorClass, validClass) {
                var $element = $(element);
                // Remove the red cross.                    
                $element.siblings("label").show();
            },
            unhighlight: function (element, errorClass, validClass) {
                var $element = $(element);
                // Remove the red cross.                    
                $element.siblings("label").remove();
            },
            submitHandler: function (label)
            {
                forgotpassword();
            }
        });
    });

    function forgotpassword() {
        var forgotemail = $("#email").val();
        var forget = 'email=' + forgotemail;
        loader('forgotsubmit', 'show', 'middle-reg');
        $.ajax({
            url: jsPath + "user/forgotpassword",
            type: "POST",
            data: forget,
            dataType: "json",
            success: function (responseText) {
                if (responseText.status == '1') {
                    $('#forgot_sucess_div').html("<div class='reset-popup'><?php echo $this->frmMsg['FORGOTLINK']; ?></div>");
                    /*$.fn.colorbox.resize({height: "",width: "420px"});
                     window.setTimeout(function() {
                     $.colorbox.close();
                     }, 7000);
                     } else {
                     toggle_loader('forgotsubmit', 'hide', '');
                     if(responseText.attemptCount == "<?php echo MAX_FORGOT_PASS_ATTEMPT; ?>"){
                     /*display captcha*/
                    /*$("#displayCaptcha").show();
                     $("#checkCaptcha").val(1);*/
                    $.fn.colorbox.resize({height: "",width: "400px"});
                    $('.modal-header h2').text('Success');
                    loader('forgotsubmit', 'hide', '');
                    $('#forgot_error').hide();
                   // $('#forgot_sucess_div').addClass('reset-popup');
                    setTimeout(function () {
                        location.reload();
                    }, 2000);

                } else {
                    loader('forgotsubmit', 'hide', '');
                    $('#forgot_error').html(responseText.msg);
                    $('#forgot_error').show();
                }
                //$.fn.colorbox.resize({height: "",width: ""});

            }
        });
        return false;
    }
    /****************************** Function for appending loader on ajax **********************************/
    /*function toggle_loader(elementId, showHide, classStyle){
     if(classStyle == undefined){
     classStyle = '';
     }
     var loaderLabel = '<div class="spinner "+ classStyle +" id = "showLoader"><div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div><div class="rect5"></div></div>';
     
     if(elementId != '' && elementId != 'undefined' && showHide != ''){
     if(showHide == 'show'){
     $(loaderLabel).insertBefore('#'+elementId);
     $('#'+elementId).hide();
     
     } 
     if(showHide == 'hide'){
     $('#showLoader').remove();
     $('#'+elementId).show();
     }
     }
     }*/
    /****************************** End loader script here ************************************/
    jQuery("#forgotPopup").center();
    $(".js-modal-close, .modal-overlay").click(function () {
        $(".modal-box, .modal-overlay").fadeOut(500, function () {
            $(".modal-overlay").remove();
        });

    });

</script>





