<!--<link rel="stylesheet" type="text/css" href="<?php echo WEBSITE_URL; ?>css/loader.css" />-->
<link rel="stylesheet" type="text/css" href="<?php echo WEBSITE_URL; ?>css/gplus.css" />
<?php $currenturl = 'http://' . $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"]; ?>
<input type="hidden" id="currenturl" name="currenturl" value='<?php echo $currenturl; ?>'>
<input type="hidden" id="type" value="<?php echo $this->type; ?>">
<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="<?php echo $this->gmailClientId; ?>">
<!-----------------------------------------------------------------------------------------new code----------------------------------------------------------------------------------------->
<div id="signup_message">
    <div class="modal-body">
        <div class="left-model-side">
            <div class="mdl-bg">
                <div class="login-logo">
                    <img src="<?php echo WEBSITE_URL; ?>images/logo2.png">
                </div>
                <h3 class="getwedding">Get Wedding – Ready!</h3>
                <ul>
                    <div class="logintext">
                        <li>45000+ Certified Wedding Vendors</li>
                        <li>32000+ Gorgeous Photo Inspirations</li> 
                        <li>Hundreds of Beautiful Real Weddings</li>
                        <li>Intelligent Wedding Planning Tools</li>
                    </div>
                </ul>
            </div>
        </div>
        <div class="right-model-side" id="popuplog">
            <!--         <a href="javascript:void(0);" id="closer" class="js-modal-close close">×</a>-->
            <div class="social-login">
                <a href="javascript:void(0);" onclick='fblogin();'>
                    <span class="sprite-log fb-log"><i class="fa fa-facebook"></i></span></a>
                <div class="g-signin2" data-onsuccess="onSignIn" style="color: #eeeeee!important;"></div>  
                <div style="clear:both;"></div>
            </div>
            <p style=" margin-left: 27px; color: #383637;">Or</p>
            <div class="login">
                <?php
                echo $this->form('adduser', array('name' => 'adduser', 'id' => 'adduser', 'class' => 'sky-form', 'method' => 'post',
                    'action' => ""));
                ?>
                <!--<form action="" class="sky-form">-->
                <fieldset>
                    <section>
                        <div id="login_error" class="fl-lt error-tip" style="display: none;"></div>
                        <div class="row">
                            <label class="input"> <i class="icon-append icon-envelope"></i>
                                <?php echo $this->formText('loginemail', '', array('id' => 'loginemail', 'name' => 'loginemail', 'placeholder' => 'Email', 'class' => 'input-txt box2')); ?>
                            </label>
                        </div>
                    </section>
                    <section>
                        <div class="row">
                            <label class="input"> <i class="icon-append icon-lock"></i>
                                <?php echo $this->formPassword('pass', '', array('id' => 'pass', 'name' => 'pass', 'placeholder' => 'Password', 'class' => 'input-txt box2 rltv')); ?> 
                                <div class="forgot-box">
                                    <a href="javascript:void(0);" onclick="javascript:forgotForm();" class="enqury">
                                        <?php echo $this->frmMsg['FORGOT']; ?>?</a>
                                </div>
                            </label>
                            <input type="hidden" name="type" id="type" value="<?= $this->type; ?>">
                        </div>
                        <div class="row">
                            <input type="submit" value="Login" class="radius-btn-loginpop" id="login" name="login" style = "font-size:16px;">
                        </div>
                    </section>
                </fieldset>
                </form>
                <span class="ls-form" style="font-size: 14px;">  Not a member yet?
                    <a href="javascript:void(0);" class="first js-open-modal btn" id="signup_text">Sign Up</a>
                </span>
            </div>
            <!------------------------------------------------------------------------------------Registration code here-------------------------------------------------------------------->
            <div class="registration">
                <div id="signup_message">
                    <?php echo $this->form('frm_register', array('name' => 'frm_register', 'class' => 'sky-form', 'method' => 'post', 'action' => "")); ?>
                    <!--<form id="frm_register" class="sky-form" method="post" action="" novalidate>-->
                    <fieldset>
                        <section>
                            <div id="register_error" class="error-tip" style="display: none;"></div>
                            <div class="row">
                                <label class="input"> <i class="icon-append icon-user"></i>
                                    <?php echo $this->formText('signupusername', '', array('id' => 'signupusername', 'name' => 'signupusername', 'placeholder' => 'Name')); ?>  
                                </label>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="input"> <i class="icon-append icon-envelope"></i>
                                    <?php echo $this->formText('email', '', array('id' => 'signupemail', 'name' => 'signupemail', 'placeholder' => 'Email Address')); ?>
                                </label>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="input"> <i class="icon-append icon-lock"></i>
                                    <?php echo $this->formPassword('signuprepass', '', array('id' => 'signuprepass', 'name' => 'signuprepass', 'placeholder' => 'Password')); ?>
                                </label>
                            </div>
                            <div class="row">
                                <input type="submit" name="join" id="join" class="radius-btn-loginpop" value="SignUp" />
                            </div>
                        </section>
                    </fieldset>
                    </form>
                    <span class="ls-form" style="font-size: 14px; padding-bottom: 12px;"> Already a member? <a href="javascript:void(0);" class="first js-open-modal btn" id="login_text">Login</a></span>
                    <span style="font-size:11px;">By signing up, you agree to our <a href="<?php echo WEBSITE_URL . "termsconditions"; ?>">terms of use</a> and <a href="<?php echo WEBSITE_URL . "privacypolicy"; ?>">privacy policy</a></span>

                </div>
    <!--            <span style="font-size:11px;">By signing up, you agree to our <a href="<?php echo WEBSITE_URL . "termsconditions"; ?>">terms of use</a> and <a href="<?php echo WEBSITE_URL . "privacypolicy"; ?>">privacy policy</a></span>-->
            </div>
        </div>
    </div>
    <div style="clear:both;"></div>
</div>
<!------------------------------------------------------------------------------------new code ends----------------------------------------------------------------------------------------------->
<!--<script type="text/javascript">
    $(".js-modal-close, .modal-overlay").click(function() {
        $(".modal-box, .modal-overlay").fadeOut(500, function() {
            $(".modal-overlay").remove();
        });
    });
</script>-->
<?php /*
  <script type="text/javascript" src="<?php echo WEBSITE_URL ?>js/tabs.min.js"></script>
  <script src="<?php echo WEBSITE_URL ?>js/tipsy-src/javascripts/jquery.tipsy.js"></script> */ ?>
<script type="text/javascript">
    jQuery("#popup1,#popup2,#popup3").center();
    /*
     $(document).ready(function() {
     
     $("#cboxClose").click(function(){
     $(".tipsy").css("display","none");
     })
     
     setTimeout(function() {
     $('input[name="loginemail"]').focus()
     }, 500);
     });
     */

    jQuery(document).ready(function () {
        var errinc = 1;
        //$('#adduser :input').tipsy({ trigger: 'manual', fade: true, gravity: 'sw' });
        $("#adduser").validate({
            onkeyup: false,
            errorClass: 'error-tip2',
            rules: {
                loginemail: {
                    required: true,
                    minlength: 5,
                    email: true
                },
                pass: {
                    required: true
                            //minlength: 5
                }
            },
            messages: {
                pass: {
                    required: '<?php echo $this->errMsg['password']['no_empty']; ?>',
                    minlength: '<?php echo $this->errMsg['password']['min_length']; ?>'
                },
                loginemail: {
                    required: '<?php echo $this->errMsg['email']['no_empty']; ?>',
                    minlength: '<?php echo $this->errMsg['email']['min_length']; ?>'
                }
            },
            success: function (label) {
                errinc = 1;
                $(label).each(function () {
                    $('#' + this.htmlFor).removeClass('error-tip2');
                    $('#login_error').html('');
                    $('#login_error').hide();
                });
            },
            errorPlacement: function (error, element) {
                if (errinc <= 1) {
                    /*error.insertAfter(element);
                     element.addClass('error-tip');*/
                    $(error).each(function () {
                        $('#login_error').html(error.text());
                        $('#login_error').show();
                        element.addClass('error-tip2');
                        errinc++;
                    })
                }
            },
            submitHandler: function (label) {
                loader('login', 'show', 'middle-load-login-tf');
                var email = $('#loginemail').val();

                var pass = $("#pass").val();
                /*		
                 if ($('#rembme').attr('checked')) {
                 var remember = 1;
                 } else {
                 var remember = 0;
                 }*/
                var remember = 1;
                //toggle_loader('login', 'show', 'middle');
                var login = 'email=' + email + '&password=' + pass + '&remember=' + remember;
                $.ajax({
                    url: jsPath + "user/login",
                    type: "POST",
                    dataType: "json",
                    data: login,
                    success: function (data) {

                        if (data.status == 1) {
                            var typeval = $('#type').val();
                            if (typeval == 'attendevent') {
                                //jQuery.colorbox.close();
                                attend();
                            } else if (typeval == 'addreview') {
                                //jQuery.colorbox.close();
                                submitreview();
                            } else {
                                var currenturl = $('#currenturl').val();
                                if ((currenturl.search("/user/login") > 0)) {
                                    //jQuery.colorbox.close();
                                    window.location.reload();
                                } else {
                                    // jQuery.colorbox.close();
                                    window.location.reload();
                                }
                            }
                        } else {
                            loader('login', 'hide', '');
                            $('#login_error').html(data.msg);
                            $('#login_error').show();
                            // $.fn.colorbox.resize({height: "", width: ""});
                            return false;
                        }
                    }
                });
            }
        });
    });
</script>

<script>
    jQuery(document).ready(function () {
        var errinc = 1;
        $('#frm_register').validate({
            onkeyup: false,
            errorClass: 'error-tip2',
//                errorClass: 'error-tip2',
            rules: {
                signupemail: {
                    required: true,
                    minlength: 5,
                    email: true
                },
                signuprepass: {
                    required: true
                },
                signupusername: {
                    required: true
                },
            },
            messages: {
                signupemail: {
                    required: "<?php echo $this->errMsg['email']['no_empty'] ?>",
                    minlength: "<?php echo $this->errMsg['email']['min_length'] ?>",
                    email: "<?php echo $this->errMsg['email']['invalid'] ?>"
                },
                signuprepass: {
                    required: "<?php echo $this->errMsg['password']['no_empty'] ?>",
                    minlength: "<?php echo $this->errMsg['password']['min_length'] ?>"
                },
                signupusername: {
                    required: "<?php echo $this->errMsg['username']['no_empty'] ?>",
                    minlength: "<?php echo $this->errMsg['username']['min_length'] ?>"
                },
            },
            success: function (label) {
                errinc = 1;
                $(label).each(function () {
                    $('#' + this.htmlFor).removeClass('error-tip2');
                    $('#register_error').html('');
                    $('#register_error').hide();
                });
            },
            errorPlacement: function (error, element) {
                if (errinc <= 1) {
                    /*error.insertAfter(element);
                     element.addClass('error-tip');*/
                    $(error).each(function () {
                        $('#register_error').html(error.text());
                        $('#register_error').show();
                        element.addClass('error-tip2');
                        errinc++;
                    })
                }
            },
            submitHandler: function (label) {
                getregister(label);
            }
        });
    });

    function getregister(label) {

        var signupusername = $("#signupusername").val();
        var signupemail = $("#signupemail").val();
        var signuppassword = $("#signuprepass").val();
        loader('join', 'show', 'middle-reg-signup');
        var joinus = 'username=' + signupusername + '&email=' + signupemail + '&password=' + signuppassword;

        $.ajax({
            url: jsPath + "user/register",
            type: "POST",
            dataType: "json",
            data: joinus,
            success: function (responseText) {
                if (responseText.msg === 'success')
                {
                    var signupusername = $("#signupusername").val();
                    //$('#signup_message').html("<div class='popupmessage'><?php //echo $this->frmMsg['THANKSJOINING'];     ?></div>");
                    //$('#loginusernametitle').html("");
                    //$('#loginusernametitle').html("Welcome");
                    //$('#someicon').show();
                    //$('#loginusername').html(signupusername);
                    //$('#signup_message').html("<span><div style='padding:10px 0 8px 14px; background-color: #e2e2e2;'>Welcome " + signupusername + "</div> <div style='width: 100%; text-align: center; padding: 30px;'><?php echo $this->frmMsg['THANKSJOINING']; ?></div></span>");
                    //$('.modal-box').css('width', '320px');
                    $("#signup_message").css({"background-image": "url(<?php echo WEBSITE_URL;?>images/signup_succes.jpg)", "background-size": "cover", "height": "300px", "border-radius": "10px"}); 
                    $("#signup_message").html("<div class='color-box-hd'></div><div id='success' class='signup-succes-hd-box' style='padding:15px 20px 15px 20px; width:100%;'>Success</div><?php echo $this->frmMsg['THANKSJOINING']; ?>");
                    $.fn.colorbox.resize({height: "300px", width: "600px;"});
                    window.setTimeout(function () {
                        var loginStr = '&email=' + signupemail + '&password=' + signuppassword;
                        $.ajax({
                            url: jsPath + "user/login",
                            type: "POST",
                            dataType: "json",
                            data: loginStr,
                            success: function (loginresponseText) {
                                if (loginresponseText.status === 1) {
                                    var currenturl = $('#currenturl').val();
                                    if ((currenturl.search("/user/login") > 0)) {
                                        window.location.reload();
                                    } else {
                                        window.location.reload();
                                    }
                                } else {
                                    loader('join', 'hide', '');
                                    $('#register_error').html(loginresponseText.msg);
                                    $('#register_error').show();
                                    return false;
                                }
                            }
                        })
                    }, 7000);
                } else { //alert(responseText.msg);
                    loader('join', 'hide', '');
                    $('#register_error').html(responseText.msg);
                    $('#register_error').show();
                    //$('#signupemail').removeClass('error-tip');
                    return false;
                }
            }
        });
        return false;
    }

    function onSignIn(googleUser) {
        var profile = googleUser.getBasicProfile();
        var value = 'id=' + profile.getId() + '&name=' + profile.getName() + '&email=' + profile.getEmail() + '&imgUrl=' + profile.getImageUrl();
        $.ajax({
            //this is the php file that processes the data
            url: jsPath + "user/getgmailsession",
            //POST method is used
            type: "POST",
            //pass the data			
            data: value,
            dataType: "json",
            //success
            success: function (data) {
                if (data.status == 1)
                {
                    window.location.reload();
                }
            }
        });
    }
</script>

<!---- login animation js ------>
<script type="text/javascript">
    $(document).ready(function (e) {
        $("#signup_text").click(function (e) {
            $(".registration").animate({
                left: "0px"
            }, 1000)
            $(".login").animate({
                left: '-350px'
            }, 1000)
        });
        $("#login_text").click(function (e) {
            $(".registration").animate({
                left: "-350px"
            }, 1000)
            $(".login").animate({
                left: '0px'
            }, 1000)
        });
    });
</script> 

<style>
    .middle-reg-signup{ margin: auto !important; margin-top: 33px!important;}
</style>

