<div id="feedbacksucess">
<div class="nyroModalTitle">We appreciate your feedback</div>
  <table width="340" border="0" cellspacing="0" cellpadding="0" >
    <tr>
      <td height="25" colspan="2" class="strong-txt td-pads">Name<span class="star">*</span>
        <div style="float:right; width:60%; color:#ab0000; text-align:right; padding-right:40px; font-size:11px;" id="feedbackerror" ></div></td>
    </tr>
    <tr>
      <td height="30" colspan="2" valign="top" class="td-pads"><input type="text" id="feedbackname" name="feedbackname" value="" onclick="deleteemail()" class="input-txt box2" /></td>
    </tr>
    <tr>
      <td height="25" colspan="2" class="strong-txt td-pads">Email<span class="star">*</span></td>
    </tr>
    <tr>
      <td height="30" colspan="2" valign="top" class="td-pads"><input type="text" id="feedbackemail" name="feedbackemail" value="" onclick="deleteemail()" class="input-txt box2" /></td>
    </tr>
    <td height="25" colspan="2" class="strong-txt td-pads">Mobile<span class="star">*</span></td>
    </tr>
    <tr>
      <td height="30" colspan="2" valign="top" class="td-pads"><input type="text" id="feedbackmobile" name="feedbackmobile" value="" onclick="deleteemail()" class="input-txt box2" /></td>
    </tr>
    <tr>
      <td height="25" colspan="2" class="strong-txt td-pads">Comments<span class="star">*</span></td>
    </tr>
    <tr>
      <td height="30" colspan="2" valign="top" class="td-pads"><textarea id="comments" name="comments" value="" onclick="deleteemail()" class="input-txt box2" />
        </textarea></td>
    </tr>
    <tr>
      <td colspan="2" valign="middle" class="td-pads pad-bottom"><input type="button" style="margin-top:5px;" id="sendfeedback"  name="sendfeedback" onclick="sendfeedback()" class="btn-pink" value="Submit" /></td>
    </tr>
</table>
</div>