<div class="container-fluid">
				<div class="content-wrap">	
				<main id="content" class="content" role="main">
				<div class="row">
				<div class="col-lg-12">
				<div class="well">
				<section class="widget" style="background-color:#FFF; margin-top:2rem">
				<table class="table">
				<tbody><tr style="background-color:#ddd">
				<th>Id</th>
				<th>First Name</th>
				<th>Lasr Name</th>
				<th>Sex</th>
				<th>DOB</th>
				<th>Status</th>
				<th>Action</th>
				<th><button type="submit" class="btn btn-success">&lt;</button>
					<button type="submit" class="btn btn-success">&gt;</button>
					</th>
				</tr>
				<tr>
				<td>0001</td>
				<td>Ramesh</td>
				<td>Rupani</td>
				<td>Male</td>
				<td>01/08/1990</td>
				<td>Active</td>
				<td><button type="submit" class="btn btn-secondary">Edit</button>
					<button type="submit" class="btn btn-success">Check Out</button>
					</td>
				<td></td>
				</tr>
				<tr>
				<td>0002</td>
				<td>Arun</td>
				<td>Kumar</td>
				<td>Male</td>
				<td>22/04/1995</td>
				<td>Active</td>
				<td><button type="submit" class="btn btn-secondary">Edit</button>
					<button type="submit" class="btn btn-success">Discharge</button>
					</td>
				<td></td>
				</tr>
				</tbody></table>
				</section>
				</div>
				</div>
				</div>
				</main>
				</div>
</div>

<script>
function cancel(url){
    window.location = url;
}
</script>
