
				<div class="col-lg-7" style="float:center; margin-left:230px">
				<div class="well">			
				<section class="widget">
				<div class="row">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-10">
				<h4 style="text-align:"> How was your appointment experience with DR.Krishna Kumar ?</h4>
				<p>Your expereience will help over 1 lac people choose the right doctor daily.</p><br>
				
				<span style="color:orange"><b>Q1. </b></span><b>Would you like to recommend the doctor?<span style="color:orange">*</span></b>
				<br>
				<table>
				<tbody><tr>
				<th style="border: 1px solid #ddd;padding:10px;margin-left:10px">
				<a href=""><span class="icon">
				<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
				</span>Yes</a></th>
				<th style="border: 1px solid #ddd;padding:10px">
				<a href=""><span class="icon">
				<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
				</span>No</a></th>
				</tr>
				</tbody></table>
				<br>
				<span style="color:orange"><b>Q2. </b></span><b>Which clinic did you visit?<span style="color:orange">*</span></b><br>
				
				<br>
				<select style="padding:5px; float:center">
				<option>
				Medplus hyderabad
				</option>
				<option>
				MaxCure
				</option>
				<option>
				Apolo
				</option>
				</select>
				<br>
				<br>
				
				<span style="color:orange"><b>Q3. </b></span><b>For which health problem/treatement did you visit?<span style="color:orange">*</span>
				</b>
				<br>
				<br>
				<select style="padding:5px; float:center">
				<option>
				fever
				</option>
				<option>
				headache
				</option>
				<option>
				Low BP
				</option>
				</select>
				<br>
				<br>
				<span style="color:orange"><b>Q4. </b></span><b>How long did you wait to be seen by the doctor?<span style="color:orange">*</span>
				</b>
				<br>
				<br>
				 <input type="radio" name="name" value="other"> Less than 15 min<br>
				 <br>
				 <input type="radio" name="name" value="other"> 15 min to 30 min<br>
				 <br>
				 <input type="radio" name="name" value="other"> 30 min to 1 hour<br> 
				 <br>
				 <input type="radio" name="name" value="other"> More than 1 hour<br>  
				<br>
				<span style="color:orange"><b>Q5. </b></span><b>What do you think can we improved?<span style="color:orange">*</span>
				</b>
				<br>
				<br>
				 <input type="checkbox" name="name" value="other"> Doctor friendliness<br>
				 <br>
				 <input type="checkbox" name="name" value="other"> Explanation of the health issue<br>
				<br>
				<input type="checkbox" name="name" value="other"> Treatement satifaction<br>  
				<br>
				 <input type="checkbox" name="name" value="other"> Value for money<br> 
				 <br>
				 <input type="checkbox" name="name" value="other"> Wait time<br> 
				<br>
				<span style="color:orange"><b>Q6. </b></span><b>Tell me about your experience with the doctor.
				</b><br>
				<span>eg. share releveant  stories which made you appreciate 'doctor friendliness'</span>
				<br>
				<br>
				<textarea type="text" name="name" placeholder="start typing here..." value="other" style="width:80%;height:10%"></textarea>
				<br>
				<br>
				<span style="font-size:11px;background-color:orange; color:#222">
				Info: All experiences go under strict moderation process before publishing 
				to check abusive language,threats, superlative comments on medical abilities and so on.</span><br>
				<br>
				<hr>
				<input type="text" name="name" placeholder=" Your Name"><br><br>
				
				<input type="text" name="name" placeholder=" Your Mail Address"><br><br>
				
				<input type="text" name="name" placeholder=" +91">
				<br>
				<br>
				<input type="checkbox"> Keep this experience publicly anonymous.<br>
				<span style="font-size:12px">Note: Your identity will be shared with doctor, doctor asks for it.</span><br><br>
				<input type="checkbox"> I want to recieve status update from Medrechaincode via WhatsApp.<br><br>
				<button type="submit" class="btn btn-primary">Submit</button><br>
				<br>
				<span style="font-size:12px">By submiting , you agree to <a href="">Term and Conditions</a><br>
				<br>
				<br>
				<br>
				</span></div>
				</div>
				</section>
				</div>
				</div>
				