<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <!-- Page content -->
       <!-- <ol class="breadcrumb">
            <li class="breadcrumb-item">Dashboard</li>
            <li class="breadcrumb-item active">Patient profile</li>
        </ol>-->

        <div class="row">
            <div class="col-md-form">
                <section class="widget">
                    <!--<header>
                        <h5>
                            Headings
                            <small>Default and customized</small>
                        </h5>
                        <div class="widget-controls">
                            <a data-widgster="expand" title="Expand" href="#" style="display: none;"><i class="glyphicon glyphicon-chevron-up"></i></a>
                            <a data-widgster="collapse" title="Collapse" href="#"><i class="glyphicon glyphicon-chevron-down"></i></a>
                            <a data-widgster="close" title="Close" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </header>-->
                    <div class="widget-body">
                         <form class="form-horizontal" action="<?php echo  $this->url(array('action' => 'savedepartment'), 'adminDepartment', true) ?>" method="POST">

                            <input type = "hidden" id ="id" name ="id" value = "<?php echo $this->formdata['id'];?>">
          
                            <fieldset>
                                <legend><strong>Add Doctor</strong> form</legend>
                                <div class="form-group row" style ="text-align: center;">
                                    
                                    <div class="col-md-11">
                                        
                                        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
            <div class="notification-error">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
        <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
            <div class="notification-suc">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
                                     
                                        
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="normal-field" class="col-md-4 form-control-label text-md-right">Name</label>
                                    <div class="col-md-7">
                                        
                                        <?php                 
                   // echo $this->formText("zoneName", $this->zoneDetails['name'], array("name" => "zoneName", "class" => "form-control"));
                ?>
                                        <input type="text" value = "<?php echo $this->formdata['name'];?>" id="p_name" class="form-control" placeholder="Department Name" name = 'p_name' required>
                                    </div>
                                </div>
                               

                            </fieldset>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="offset-md-4 col-md-7 col-12">
                                        <span id = "sve_btn"><button type="submit" class="btn btn-primary" id = 'button'>Save</button></span>
                                        <button type="button" class="btn btn-inverse" id = "search" onClick = "javascript:cancel('patient/index');">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div id = "f-l-name"></div>
                    </div>
                </section>
            </div>

        </div>
       </main>
</div>
    </div>

