<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/jquery-ui.min.css">
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/ui.jqgrid.min.css">
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/ui.jqgrid.css"/>
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/qunit-2.6.2.css">


<script src="<?php echo WEBSITE_URL; ?>js/jqgrid/jquery.jqgrid.min.js"></script>
<div class="container-fluid">
    <div class="content-wrap">	
        <main id="content" class="content" role="main">
            <div class="row">
                <div class="col-lg-12">
                    <div class="well">
                        <section class="widget" style="background-color:#FFF; margin-top:2rem">
                            <div id="gridWidth" class="left">
                                <table id="jqGrid" width="50%" border="0" cellpadding="0" cellspacing="0"></table>
                                <div id="jqGridPager"></div> <!-- new location pager --><!-- <div id="pager2"></div> old location pager -->
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>





<script language="javascript">
    $(document).ready(function () {
        grid_function();
    });
    function grid_function() {
        $('#gridWidth').html('<div id="gridWidth" class="left"><table id="jqGrid" width="100%" border="0" cellpadding="0" cellspacing="0"></table><div id="pager2"></div></div>');
        var statusStr = "<?php echo LAB_REQUEST_STATUS; ?>";
        $.jgrid.no_legacy_api = true;
        $.jgrid.useJSON = true;
        var grid = jQuery("#jqGrid");
        var pages = []; // not as {};
        var emptyMsgDiv = $('<div class="no-record-msz"><?php echo RESULT_NOT_FOUND; ?></div>');
        jQuery("#jqGrid").jqGrid({
            url: nursePath + 'immunization-requests/index',
            datatype: "json",
            colNames: [
                'Req Id',
                'Appnt ID',
                'Registration No',
                'Patient Name',
                'Test Name', 'Doctor name', 'Requested Date', 'Status','Action'
            ],
            colModel: [
                {name: 'id', index: 'id', align: 'center', width: 30, search: true, sortable: false, editable: false},
                {name: 'appointment_id', index: 'appointment_id', align: 'center', width: 30, search: true, sortable: false, editable: false},
                {name: 'registration_no', index: 'registration_no', align: 'center', width: 50, search: true, sortable: false, editable: false, editrules: {required: true}, edittype: 'text'},
                {name: 'patient_name', index: 'patient_name', align: 'center', width: 60, search: true, sortable: false, editable: false, editrules: {required: true}, edittype: 'text'},
                {name: 'lab_test_name', index: 'lab_test_name', align: 'center', width: 70, search: false, sortable: false, formatter: ''},
                {name: 'doctor_name', index: 'doctor_name', align: 'center', width: 60, search: false, sortable: true},
                {
                    name: 'created_at',
                    index: 'created_at',
                    align: 'center',
                    width: 50,
                    searchoptions: {
                        // dataInit is the client-side event that fires upon initializing the toolbar search field for a column
                        // use it to place a third party control to customize the toolbar
                        dataInit: function (element) {
                            $(element).datepicker({
                                id: 'orderDate_datePicker',
                                dateFormat: 'd-m-yy',
                                minDate: new Date(2010, 0, 1),
                                maxDate: new Date(2030, 0, 1),
                                showOn: 'focus'
                            });
                        },
                        // show search options
                        sopt: ["ge", "le", "eq"] // ge = greater or equal to, le = less or equal to, eq = equal to
                    }
                },
                {name: 'status', index: 'status',align:'center', width: 70, sortable: false, title: false, formatter: '', editable: true, editrules: {required: true}, edittype: 'select', editoptions: {
                        value: statusStr}, stype: "select",
                    searchoptions: {
                        value: statusStr,
                        defaultValue: ""
                    }},
                {name: 'actions', index: 'actions',align:'center', width: 30, search: false, title: false, sortable: false, formatter:''}
                //{name: '', align: 'center', width: 40, sortable: false, search: false, formatter: ''},               
                //{name: '', align: 'center', width: 40, sortable: false, search: false, formatter: ''},               
                ],
            onSelectRow: function (rowid, status, e) {
                if (e != undefined) {
                    var selectedValue = $('#myGrid').getCell(rowid, 'col1');
                    if (selectedValue) {
                        $('#myGrid').jqGrid('setColProp', 'col1', {editable: true});
                    }
                }
            },
            rowNum:<?php echo NO_OF_RECORDS_PER_PAGE; ?>,
            mtype: 'post',
            width: jQuery('#gridWidth').width(),
            height: 'auto',
            rowList: [<?php echo ROWLIST; ?>],
            pager: '#pager2',
            sortname: 'id',
            sortorder: "DESC",
            caption: "Lab Request List",
            autosearch: true,
            toppager: false,
            viewrecords: true,
            altRows: true,
            altclass: 'grid-Alternate-Row',
            rownumbers: true,
            recordtext: "View {0} - {1} of {2}",
            emptyrecords: false,
            /*loadtext: "Loading",*/
            width: 900,
                    multiselect: false, // <------like here or your choice.
            hoverrows: false,
            //editurl: '',
            loadComplete: function () {
                var count = grid.getGridParam();
                var ts = grid[0];
                if (ts.p.reccount === 0) {
                    grid.hide();
                    emptyMsgDiv.show();
                } else {
                    grid.show();
                    emptyMsgDiv.hide();
                }
            }
        });
        // place div with empty message insde of div
        emptyMsgDiv.insertAfter(grid.parent());
        emptyMsgDiv.hide();
        jQuery("#jqGrid").jqGrid('navGrid', '#pager2', {edit: false, add: false, del: false, search: false}, {closeAfterEdit: true, closeOnEscape: true}, {closeAfterAdd: true, closeOnEscape: true});
        jQuery('#jqGrid').jqGrid('filterToolbar', {"stringResult": true, searchOnEnter: true});
        myGrid = jQuery("#jqGrid");

        var cm = myGrid[0].p.colModel;
        $.each(myGrid[0].grid.headers, function (index, value) {
            var cmi = cm[index], colName = cmi.name;
            if (!cmi.sortable && colName !== 'rn' && colName !== 'cb' && colName !== 'subgrid') {
                $('div.ui-jqgrid-sortable', value.el).css({cursor: "default"});
            }
        });
    }

function updateStatus(id,pid) {

        var status_value = $('#status_' + id).val();

       

        if (status_value == '0') {
            alert('Select another status');
            $('#status_' + id).addClass("highlight");
            $('#status_' + id).focus();
            //$('#remarks_' + claimedBusinessId).removeClass("highlight");
            return false;
        }

        if (status_value != '0') {

            var condel = confirm('Do you really want to change this status?');
            if (condel == false) {
                $('#status_' + id).addClass("highlight");
                $('#status_' + id).focus();
                $('#remarks_' + id).removeClass("highlight");
                return false;
            }
        }


        var values = 'id=' + id + '&status=' + status_value+'&pid='+pid;
        $.ajax({
            url: nursePath + "immunization-requests/updatestatus",
            type: "POST",
            data: values,
            success: function (responseText) {
                if (responseText == 1) {
                    alert('Status sucessfully updated.');
                    //var status = '0';
                    location.reload();

                }else if(responseText == 2){
                    
                    alert('Test Result not completed yet.');
                    //var status = '0';
                    //location.reload();
                    
                }else if(responseText == 3){
                    
                    alert('Please select another status option.');
                    //var status = '0';
                    //location.reload();
                    
                }

            }
        });

    }

   

    
    
    function toggle_loader(elementId, showHide, classStyle) {
        if (classStyle == undefined) {
            classStyle = '';
        }
        var clsName = '';
        clsName = '"spinner ' + classStyle + '"';
        var loaderLabel = '<div class = ' + clsName + ' id = "showLoader"><div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div><div class="rect5"></div></div>';

        if (elementId != '' && elementId != 'undefined' && showHide != '') {
            if (showHide == 'show') {
                $(loaderLabel).insertBefore('#' + elementId);
                $('#' + elementId).hide();

            }
            if (showHide == 'hide') {
                $('#showLoader').remove();
                $('#' + elementId).show();
            }
        }
    }

  

    $.extend($.fn.fmatter, {
        actionFormatter: function (cellvalue, options, rowObject) {
            var retVal = "<a onclick='return patientEdit(" + options.rowId + ");' href='javascript:void(0);'><span class='ui-icon ui-icon-pencil'></span></a>";
            return retVal;
        }
    });

</script>
<style>
    .ui-jqgrid .ui-search-input select {
        width: 100% !important;
        border:1px;
    }

    .ui-jqgrid .ui-jqgrid-view select {
        font-size: 11px;
        width: 116px;
    }  


    .ui-jqgrid .ui-jqgrid-view input[type="text"] {
        font-size: 11px;
        height: 22px;
        padding: 0;
        width: 119px;
    }
</style>
