<div class="container-fluid">
    <div class="content-wrap">	
        <main id="content" class="content" role="main">

            <div class="row">
                <div class="col-lg-12">
                    <div class="well">
                        <section class="widget" style="background-color:#FFF; margin-top:2rem">
                            <form style="padding:15px" name = "frmPatentRegister" id = "frmPatentRegister" method="POST" action ="<?php echo  $this->url(array('action' => 'register'), 'hospitalPatient', true) ?>">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b> Name</b></label>
                                            <input class="form-control" type="text" id="example-date-input-name" name = "name">
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Sex</b></label>
                                            <select class="custom-select" name ="sex" id ="sex">
                                                <option selected="">Please Select</option>
                                                <option value="m">Male</option>
                                                <option value="f">Female</option>
                                                
                                    
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Date Of Birth</b></label>
                                            <input class="form-control" type="date" value="Date" id="example-date-input-dob" name = "dob">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Age</b></label>
                                            <input class="form-control" type="text" id="example-date-input-age" name = "age">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Place Of Birth</b></label>
                                            <input class="form-control" type="text" id="example-date-input-pob" name = "pob">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Occupation</b></label>
                                            <input class="form-control" type="text" id="example-date-input-occupation" name = "occupation">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Religion</b></label>
                                            <input class="form-control" type="text" id="example-date-input-religion" name = "religion">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Material Status</b></label>
                                            <select class="custom-select" name ="matrial_status" id ="matrial_status">
                                                <option selected="">Please Select</option>
                                                <option value="1">Married</option>
                                                <option value="2">Unmarried</option>
                                                
                                
                                            </select>
                                        </div>
                                        
                                        
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Address</b></label>
                                            <input class="form-control" areateaxt="text" id="example-date-input-address" name = "address">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>City</b></label>
                                            <input class="form-control" type="text" id="example-date-input-city" name = "city">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Pin</b></label>
                                            <input class="form-control" type="text" id="example-date-input-pin" name = "pin">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Phone No</b></label>
                                            <input class="form-control" type="text" id="example-date-input-mobile_no" name = "mobile_no">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Email Id</b></label>
                                            <input class="form-control" type="text" id="example-date-input-email_id" name = "email_id">
                                        </div>
                                        
                                        
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Date Of Admission</b></label>
                                            <input class="form-control" type="date" value="Date" id="example-date-input-doa" name = "doa">
                                        </div>
                                        
                                        
                                         <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Specialization</b></label>
                                            <select class="custom-select" name ="specialization" id ="specialization">
                                                <option selected="">Please select</option>
                                                <option value="1">Aman</option>
                                                
                                    
                                            </select>
                                        </div>
                                       
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Doctor</b></label>
                                            <select class="custom-select" name ="doctor" id ="doctor">
                                                <option selected="">Please select</option>
                                                <option value="1">Aman</option>
                                                
                                    
                                            </select>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Drug Allergy</b></label>
                                            <input class="form-control" type="text" id="example-date-input-drug_allergy" name = "drug_allergy">
                                        </div>
                                        <!--				  <div class="form-group">
                                                                                <label for="exampleInputEmail1"><b>External Patient Id</b></label>
                                                                                <input class="form-control" type="text" id="example-date-input">
                                                                          </div> -->
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Blood Group</b></label>
                                            <select class="custom-select" name ="blood_group" id ="blood_group">
                                                <option selected="">A+</option>
                                                <option value="1">B+</option>
                                                <option value="2">AB+</option>
                                                <option value="3">AB-</option>
                                                <option value="3">A-</option>
                                                <option value="3">B-</option>
                                                <option value="3">O+</option>
                                                <option value="3">O-</option>

                                            </select>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Referred By</b></label>
                                            <input class="form-control" type="text" id="example-date-input-referred_by" name = "referred_by">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Height</b></label>
                                            <input class="form-control" type="text" id="example-date-input-height" name = "height">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Weight</b></label>
                                            <input class="form-control" type="text" id="example-date-input-weight" name = "weight">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Relation</b></label>
                                            <select class="custom-select" name ="relation" id ="relation">
                                                <option selected="s/o">S/O</option>
                                                <option value="w/o">W/O</option>
                                                <option value="m/o">M/O</option>
                                                <option value="h/o">H/O</option>
                                    
                                            </select>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Relative Name/Gourdian</b></label>
                                            <input class="form-control" type="text" id="example-date-input-relative_name" name = "relative_name">
                                        </div>
<!--                                        <div class="form-group">
                                            <label for="exampleInputEmail1"><b>Payment Profile</b></label>
                                            <select class="custom-select" name = "payment_option" id = "payment_option">
                                                <option selected="">Online</option>
                                                <option value="1">Cash</option>
                                                <option value="2">UPI</option>
                                            </select>
                                        </div>-->
                                    </div>
                                </div>
                                <hr>
                                <!--					<button type="submit" style="text-align:right" class="btn btn-success">Add Address</button>-->

                                <div class="row">
                                    <div class="col-sm-6">
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        
                                    </div>
                                </div>
                                <button type="submit" style="text-align:right" class="btn btn-danger">Cancel</button>

                                <button type="submit" style="text-align:right" class="btn btn-success" name = "add">Add</button>

                            </form>
                        </section>
                    </div>
                </div>
            </div>

        </main>
    </div>	
</div>

<script>
    function cancel(url) {
        window.location = url;
    }
</script>
