
<style>
.box {
  background-color: white;
  width:192px;
  border: 7px solid blue;
  padding: 7px;
  margin: 7px;
  float:left;
}
.boxes{
    padding: 7px;
  margin-left: 5%;
    
}
</style>

<div class = "boxes">

<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital"> Registration </a></B>
    <img src="https://img.icons8.com/dusk/64/000000/edit-user-male.png">
</div>

<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Ward & Bed</a></B>
<img src="https://img.icons8.com/color/64/000000/hospital-room--v1.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Billing Mgmt.</a></B>
	<img src="https://img.icons8.com/plasticine/64/000000/billing-machine.png">
 </div>
 <div class = "box" > <B><a href ="<?php echo HOSTPATH; ?>hospital">Doctor Fee.</a></B>
<img src="https://img.icons8.com/android/64/000000/money-bag-franc.png">
  </div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Appointment</a></B>
<img src="https://img.icons8.com/cute-clipart/64/000000/calendar-minus.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Radiology Mgt.</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/xray.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Blood-Bank</a></B>
<img src="https://img.icons8.com/cotton/64/000000/--bloodbag.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Diet & Kitchen</a></B>
<img src="https://img.icons8.com/color/64/000000/kitchen-room.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Central Sterile</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/xray.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Bio Waste</a></B>
<img src="https://img.icons8.com/dusk/64/000000/waste.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Payroll & HRD</a></B>
<img src="https://img.icons8.com/dusk/64/000000/money-transfer.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Helpdesk</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/headset.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Housekeeping</a></B>
<img src="https://img.icons8.com/officel/64/000000/vacuum-cleaner.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Laundary</a></B>
<img src="https://img.icons8.com/office/64/000000/carpet-man.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Record</a></B>
<img src="https://img.icons8.com/doodle/64/000000/treatment-list.png">
</div>

<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Patient Portal</a></B>
<img src="https://img.icons8.com/pastel-glyph/64/000000/heart-monitor.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Asset Mgt.</a></B>
<img src="https://img.icons8.com/plasticine/64/000000/company-assets-.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Security Mgt.</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/security-time.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Administration</a></B>
<img src="https://img.icons8.com/dusk/64/000000/admin-settings-male.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Doctor fee</a></B>
<img src="https://img.icons8.com/android/64/000000/money-bag-franc.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Incident Mgt.</a></B>
<img src="https://img.icons8.com/nolan/64/ticket.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Finance</a></B>
<img src="https://img.icons8.com/windows/64/000000/finance-portal.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Patient</a></B>
<img src="https://img.icons8.com/officel/64/000000/call-in-bed.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Immunization</a></B>
<img src="https://img.icons8.com/nolan/64/syringe.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Ambulance</a></B>
<img src="https://img.icons8.com/doodle/64/000000/ambulance.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">TPA</a></B>
<img src="https://img.icons8.com/dotty/64/000000/car-insurance-card.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Sms Setting</a></B>
<img src="https://img.icons8.com/cute-clipart/64/000000/sms.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Certificate</a></B>
<img src="https://img.icons8.com/doodle/64/000000/certificate.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Accounting</a></B>
<img src="https://img.icons8.com/nolan/64/ledger.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Reporting</a></B>
<img src="https://img.icons8.com/cotton/64/000000/business-report.png">
</div>
    
 

    
    
    
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Laboratary</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/science-application.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Pharmacy Mgt.</a></B>
<img src="https://img.icons8.com/dusk/64/000000/prescription-pill-bottle.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">IPD</a></B>
<img src="https://img.icons8.com/nolan/64/hospital-bed.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">OPD</a></B>
<img src="https://img.icons8.com/officel/64/000000/front-desk.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Hospice</a></B>
<img src="https://img.icons8.com/color/64/000000/wheelchair.png">
</div>
<div class = "box" ><B><a href ="<?php echo HOSTPATH; ?>hospital">Staff Roaster</a></B>
<img src="https://img.icons8.com/ios-filled/64/000000/time-card.png">
</div>
    
    </div>


