



	
		<div class="container">
		<div class="wrap">
		<h2>MedReChainCode Patient Registration</h2>
		</div>
		<div class="row">
		<div class="col-sm-8">
		<section class="widget">
		<form class="form-horizontal" action="<?php echo  $this->url(array('action' => 'savepatient'), 'patientUser', true) ?>" method="POST">

                            <input type = "hidden" id ="id" name ="id" value = "<?php echo $this->formdata['id'];?>">
          
		
		<h5>Create Your Patient Account</h5>
			<div class="row">
			<div class="col-sm-2">
					<select type="text" id="code" class="form-control" placeholder="+91">
					<option>+91</option>
					<option>+81</option>
					<option>+71</option>
					<option>+61</option>
					</select>
				</div>			
				<div class="col-sm-4">
					<input type="text" id="pnumber" class="form-control" placeholder="Enter a valid phone number" name = 'pnumber'>
				</div>
			</div>&nbsp;
			<div class="row">
			<div class="col-sm-6">
			<input type="text" id="pnumber" class="form-control" placeholder="Email address" name = 'pnumber'>&nbsp;
			<input type="text" id="pnumber" class="form-control" placeholder="First Name" name = 'pnumber'>&nbsp;
			<input type="text" id="pnumber" class="form-control" placeholder="(dd/mm/yyyy)" name = 'pnumber'>&nbsp;
			
			</div>
			<div class="col-sm-6">
			<input type="text" id="pnumber" class="form-control" placeholder="Password(combo of alphnumerics & symbols" name = 'pnumber'>&nbsp;
			<input type="text" id="pnumber" class="form-control" placeholder="Last Name" name = 'pnumber'>&nbsp;
			<select type="text" id="code" class="form-control" placeholder="Gender">&nbsp;
					<option>Gender</option>
					<option>Male</option>
					<option>Female</option>
					<option>Others</option>					
					</select>
			</div>&nbsp;
			
			<p><input type="checkbox" name="agrement" value="checkbox">
			I have read and agree to the <a href="#">Patient Terms</a></p>
			<button type="button" style="background:#f09e07;color:#FFF;	font-size:25px;"class="button3" value="submit">Sign Up</button>
		
			
			</div>
                        </form>
			</section>
			</div>
			<div class="col-sm-3">
			</div>
			</div>
		</div>
