

 <link href="<?php echo WEBSITE_URL; ?>css/doctor-list/application.min.css" rel="stylesheet">
 <link href="<?php echo WEBSITE_URL; ?>css/doctor-list/animate.css" rel="stylesheet">
		<link href="<?php echo WEBSITE_URL; ?>css/doctor-list/application_new.css" rel="stylesheet">
        
		<div class="container-fluid">
			<div class="content-wrap">
				<main id="content" class="content" role="main">
				 <div class="row">
				                          
				 <input style=" width: 50%; font-size: 14px; padding: 8px; border: 1px solid #222;"
					type="text" id="mySearch" onkeyup="myFunction()" placeholder="Search doctor, clinics, hospitals, etc " title="Type in a category">
					 <button type="submit"><i class="fa fa-search"></i></button>
				</div>
				</main>
			</div>
			
			
		</div>
		<div class="container-fluid">
			<div class="content-wrap">
				<main id="content" class="content" role="main">
				<div class="col-lg-9">
				<div class="well">			
				<section class="widget">
				<div class="row">
					<div class="col-sm-2">
					<img src="<?php echo WEBSITE_URL; ?>/images/doctor.jpg" alt="" >
					</div>
					<div class="col-sm-6">
					<a href="#"><h5>Dr.Krishna Kumar</h5></a>
					<p>MBBS</p>
					<p>10 Years Experience Overall</p>
					<p style="background-color:#ddd; width:15%">Allopath</p>
					<p>General Physician</p>
					
					</div>
					<div class="col-sm-3">
					<div>
					 <span class="icon">
					 <i class="fa fa-thumbs-o-up"></i>	
					<span style="color:green;font-weight:bold">85%</span>
					<br>
					</span>
					</div>
					 <span class="icon">
					 <i class="fa fa-comment"></i>	
					7 Patients Experienced
					</span><br>
					
					 <span class="icon">
					 <i class="fa fa-map-marker"></i>	
					 
					</span>jubilee hills<br>			
					 <span class="icon">
					 <i class="fa fa-money"></i>	
					
					</span>	
					$ 12	<br>				
					 <span class="icon">
					 <i class="fa fa-clock"></i>
					</span>
					<span class="" style="color:green; font-weight:bold">
					Today Available	</span>
					<hr>
					
					</div>
					
					<hr>
					</div>
					<div class="row">
					<div class="col-sm-4">
					</div>
					<div class="col-sm-4">
					<a href="view-profile.php">View Profile</a>
					 <button type="submit" class="btn btn-primary" value="submit">Contact Hospital</button>
					</div>
					<div class="col-sm-3">
					 <button type="submit" class="btn btn-primary" value="submit"><a href="book-appointment.php" style="color:#fff">Book Appointment</a></button>
					</div>
					</div>
				
				
				
				</section>
				</div>
				</div>
				</main>
			</div>
			
			
		</div>
		