<div class="container-fluid">
       <div class="content-wrap">
            <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
            <main id="content" class="content" role="main">
                <!-- Page content -->
        <!--<h1 class="page-title">
            Analytics
            <small>
                <small>Summarized company performance</small>
            </small>
        </h1>-->
        <div class="analytics">
            <div class="analytics-side">
                <div class="row">

                <table id="example" class="table table-striped table-bordered" style="width:82%">
        <thead>
            <tr>
                <th>#</th>
                <th>Salary Grade</th>
                <th>Basic Salary</th>
                <th>Overtime Rate</th>
                <th>Action</th>
               
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Tiger Nixon</td>
                <td>System Architect</td>
                <td>Edinburgh</td>
                <td>kumar.roushan@gmail.com</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check">
          </span></a><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-edit">
        </span></a><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-trash">
      </span> 
    </a></td>
               
            </tr>
            <tr>
                <td>Garrett Winters</td>
                <td>Accountant</td>
                <td>Tokyo</td>
                <td>63</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check">
        </span></a><a href="#" class="btn btn-success btn-lg">
      
      <span class="glyphicon glyphicon-edit">
        </span></a><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-trash">
          
      </span> 
    </a></td>
               
            </tr>
            <tr>
                <td>Ashton Cox</td>
                <td>Junior Technical Author</td>
                <td>San Francisco</td>
                <td>66</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check">
           
      <span class="glyphicon glyphicon-edit">
        </span></span></a><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-trash">
      </span> 
    </a></td>
                
            </tr>
            <tr>
                <td>Cedric Kelly</td>
                <td>Senior Javascript Developer</td>
                <td>Edinburgh</td>
                <td>22</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check">
           
      <span class="glyphicon glyphicon-edit">
        </span></span></a><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-trash">
      </span> 
    </a></td>
                
            </tr>
            <tr>
                <td>Airi Satou</td>
                <td>Accountant</td>
                <td>Tokyo</td>
                <td>33</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check"></span> 
    </a></td>
                
            </tr>
            <tr>
                <td>Brielle Williamson</td>
                <td>Integration Specialist</td>
                <td>New York</td>
                <td>61</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check"></span> 
    </a></td>
                
            </tr>
            <tr>
                <td>Herrod Chandler</td>
                <td>Sales Assistant</td>
                <td>San Francisco</td>
                <td>59</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check"></span> 
    </a></td>
                
            </tr>
            <tr>
                <td>Rhona Davidson</td>
                <td>Integration Specialist</td>
                <td>Tokyo</td>
                <td>55</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check"></span> 
    </a></td>
                
            </tr>
            
            <tr>
                <td>Dai Rios</td>
                <td>Personnel Lead</td>
                <td>Edinburgh</td>
                <td>35</td>
                <td><a href="#" class="btn btn-success btn-lg">
      <span class="glyphicon glyphicon-check"></span> 
    </a></td>
                
            </tr>
            </tbody>




</table>  
                </div>
              
            </div>
            <div class="analytics-side">
             
        </div>
                    <footer class="content-footer">
                       
                    </footer>
            </main>
        </div>
				</div>
    </div>