<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <section class="widget">
		 <div class="widget-body">
			
			<div>
			https://www.google.com/maps/place/Poona+Hospital+And+Research+Centre/@18.5060097,73.8356882,13z/data=!4m8!1m2!2m1!1spune+hospital!3m4!1s0x0:0x54d12ea7498c2ebe!8m2!3d18.5108861!4d73.8421476</div>
			</div>
       </section>
       </main>
</div>
    </div>

<script language="javascript">


</script>

