<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <!-- Page content -->
       <!-- <ol class="breadcrumb">
            <li class="breadcrumb-item">Dashboard</li>
            <li class="breadcrumb-item active">Patient profile</li>
        </ol>-->

        <div class="row">
            <div class="col-md-form">
                <section class="widget">
                    <header>
                       
                        <div class="widget-controls">
                            <a data-widgster="expand" title="Expand" href="#">Patient vital Details </a>
                            <a data-widgster="collapse" title="Collapse" href="#">Patient Hospital Details </a>
                            <a data-widgster="close" title="Close" href="#">Patient Prescription Details </a>
                        </div>
                    </header>
                    <div class="widget-body">
                         <form class="form-horizontal" action="<?php echo  $this->url(array('action' => 'savemedicalreport'), 'patientHealth', true) ?>" method="POST" enctype="multipart/form-data">

                            <input type = "hidden" id ="id" name ="id" value = "<?php echo $this->formdata['id'];?>">
          
                            <fieldset>
                                
                                <legend><strong>Add/Update </strong> Patient Medical Report Details</legend>
                                
                                
                                <div class="form-group row" style ="text-align: center;">
                                    
                                    <div class="col-md-11">
                                        
                                        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
            <div class="notification-error">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
        <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
            <div class="notification-suc">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } 
        
        //print_r($this->formdata);
        ?>
                                     
                                        
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="normal-field" class="col-md-4 form-control-label text-md-right">Test Name</label>
                                    <div class="col-md-7">
                                        
                                        <?php                 
                   // echo $this->formText("zoneName", $this->zoneDetails['name'], array("name" => "zoneName", "class" => "form-control"));
                ?>
                                        <input type="text" value = "<?php echo $this->formdata['test_name'];?>" id="p_name" class="form-control" placeholder="Test Name" name = 'test_name' required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-4 control-label text-md-right" for="tooltip-enabled">Test Date/Time</label>
                                    <div class="col-md-7 input-group date" id="datetimepicker4" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4" name = "test_date" value="<?php echo $this->formdata['test_date'];?>">
                                        <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="hint-field" class="col-md-4 control-label text-md-right">
                                        Test Result
                                        <!--<span class="help-block">Some help text</span>-->
                                    </label>
                                    <div class="col-md-7">
                                        
                                        
                                        <input type="text" value = "<?php echo $this->formdata['test_result'];?>" id="hint-field" class="form-control" name = 'test_result' required>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-md-4 form-control-label text-md-right" for="fileupload1">
                                        Attach Medical Report
                                    </label>
                                    <div class="col-md-7">
                                        <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                            <div class="form-control" data-trigger="fileinput">
                                                <i class="glyphicon glyphicon-file fileinput-exists"></i>
                                                <span class="fileinput-filename" id = 'fileinput_filename'></span>
                                            </div>
                                            <button type = "button" class="input-group-addon btn btn-default btn-file">
                                                <span class="fileinput-new">Select file</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input id="fileupload1" name="medical_report_filename" type="file" onChange="displayFileName();">
                                            </button>
                                            <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                        </div>
                                        <span class="help-block"><a target = "_blank" href = "<?php echo UPLOADED_REPORT_FILE_PATH.$this->formdata['medical_report_filename'];?>"><?php echo $this->formdata['medical_report_filename'];?>(<?php echo $this->formdata['hash_medical_report_filename'];?>)</a></span>
                                        <span class="help-block">Supported formats:pdf,jpeg,jpg</span>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-md-4 control-label text-md-right" for="tooltip-enabled">Note</label>
                                    <div class="col-md-7">
                                        <input type="text" value = "<?php echo $this->formdata['note'];?>" id="tooltip-enabled" class="form-control" data-placement="top" data-original-title="Some explanation text here" placeholder="Note" name = 'note' required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-4 control-label text-md-right" for="tooltip-enabled">Prescribed By</label>
                                    <div class="col-md-7">
                                        <input type="text" value = "<?php echo $this->formdata['prescribed_by'];?>" id="tooltip-enabled" class="form-control" data-placement="top" data-original-title="Some explanation text here" placeholder="Prescribed By" name = 'prescribed_by' required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-4 control-label text-md-right" for="tooltip-enabled">Test Center</label>
                                    <div class="col-md-7">
                                        <input type="text" value = "<?php echo $this->formdata['test_center'];?>" id="tooltip-enabled" class="form-control" data-placement="top" data-original-title="Some explanation text here" placeholder="Test Center" name = 'test_center' required>
                                    </div>
                                </div>
                          
                                


                            </fieldset>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="offset-md-4 col-md-7 col-12">
                                        <span id = "sve_btn"><button type="submit" class="btn btn-primary" id = 'button'>Save</button></span>
                                        <button type="button" class="btn btn-inverse" id = "search" onClick = "javascript:cancel('health/medical-report-details');">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div id = "f-l-name"></div>
                    </div>
                </section>
            </div>

        </div>
       </main>
</div>
    </div>

<script type='text/javascript'>

    
    function displayFileName(){
        
        var filename = $('#fileupload1').val();
        //alert(filename);
        $('#fileinput_filename').html(filename);
    }
</script>