<div class="container-fluid">
       <div class="content-wrap">
            <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
            <main id="content" class="content" role="main">
                <!-- Page content -->
        <!--<h1 class="page-title">
            Analytics
            <small>
                <small>Summarized company performance</small>
            </small>
        </h1>-->
        <div class="analytics">
            <div class="analytics-side">
                <div class="row">

                    <img src="<?php echo WEBSITE_Image; ?>/img/poc.jpg" alt="..." style = "height:800px;" />
                </div>
              
            </div>
            <div class="analytics-side">
             
        </div>
                    <footer class="content-footer">
                       
                    </footer>
            </main>
        </div>
				</div>
    </div>