<div id="footer">
        	<div class="container_12">
            	<div class="grid_12">
                	<!-- You can change the copyright line for your own -->
                	<p>Copyright © 2011. Virtual Space. All Rights Reserved.<a title="Visit For 360virtualspace" href="http://360virtualspace.com/"> Developed by 360virtualspace Technologies</a></p>
        		</div>
            </div>
            <div style="clear:both;"></div>
        </div>