<!DOCTYPE html>
<html>
    <head>
        <title>MEDRECHAINCODE</title>
        
        
        <link href="<?php echo WEBSITE_URL;?>css/application_new.css" rel="stylesheet">
        <link href="<?php echo WEBSITE_URL;?>css/application.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="img/favicon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="description" content="Medicall - Medicall">
        <meta name="keywords" content="">
        <meta name="author" content="">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <script src="<?php echo WEBSITE_URL; ?>js/jqgrid/jquery-3.3.1.min.js"></script>
            <script src="https://kit.fontawesome.com/ae2ef66705.js"></script>
             <script>
    var jsPath = '<?php echo WEBSITE_URL ?>';
    var doctorPath = jsPath+'doctor/';
</script>
    </head>
    <body>
        <nav id="sidebar" class="sidebar" role="navigation">
            <!-- need this .js class to initiate slimscroll -->
            <div class="js-sidebar-content" id = "sideBarDiv">
        <?php echo $this->render('common/doctorheader.phtml') ?>
        <?php echo $this->render('common/doctorsidebar.phtml') ?>
                </div>
        </nav>
        <?php echo $this->render('common/doctorinnerheader.phtml') ?>
        <?php echo $this->render('common/doctorinnerheader.phtml') ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->render('common/doctorfooter.phtml') ?>
        
    </body>
</html>
       


