
<div>
    <ul class="sidebar-nav">
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="#">
                <span class="icon">
                    <i class="fa fa-h-square"></i>
                </span>
                Admin
            </a>
        </li>
    </ul>
    <!-- every .sidebar-nav may have a title -->
    <!--<h5 class="sidebar-nav-title">Patients <a class="action-link" href="#">
         <!--<i class="glyphicon glyphicon-refresh"></i></a></h5>-->
    <ul class="sidebar-nav">
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo ADMIN_BASE_URL; ?>doctor/">
                <span class="icon">
                    <i class="fas fa-users"></i>

                </span>
                Doctors
            </a>
        </li>

        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo ADMIN_BASE_URL; ?>department/">
                <span class="icon">
                    <i class="fas fa-calendar-alt"></i>
                </span>
                Departments
            </a>
        </li>
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo ADMIN_BASE_URL; ?>patient/">
                <span class="icon">
                    <i class="fas fa-calendar-alt"></i>
                </span>
                Patient
            </a>
        </li>



    </ul>
</div>


