

<!-- seems like lots of recent admin template have this feature of user info in the sidebar.
     looks good, so adding it and enhancing with notifications -->
<!--                <div class="sidebar-status d-md-none">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="thumb-sm avatar float-right">
                            <img class="rounded-circle" src="demo/img/people/a5.jpg" alt="...">
                        </span>
                        
                        <span class="circle bg-warning fw-bold text-gray-dark">
                            13
                        </span>
                        &nbsp;
                        Roushan <strong>Kumar</strong>
                        <b class="caret"></b>
                    </a>
                    </div>-->
<!-- main notification links are placed inside of .sidebar-nav -->
<div>
    <ul class="sidebar-nav">
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="#">
                <span class="icon">
                    <i class="fa fa-h-square"></i>
                </span>
                DOCTOR
            </a>
        </li>
    </ul>
    <!-- every .sidebar-nav may have a title -->
    <!--<h5 class="sidebar-nav-title">Patients <a class="action-link" href="#">
         <!--<i class="glyphicon glyphicon-refresh"></i></a></h5>-->
    <ul class="sidebar-nav">
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/patient">
                <span class="icon">
                    <i class="fas fa-users"></i>

                </span>
                Patients
            </a>
        </li>

        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/appointment">
                <span class="icon">
                    <i class="fas fa-calendar-alt"></i>
                </span>
                Appointments
            </a>
        </li>
        <!--	
<li class="">                      
<a href="medicine_history.php">
<span class="icon">
<i class="fas fa-user"></i>
</span>
Medical History
</a>
</li>-->

        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/appointment/video-consultation-list">
                <span class="icon">
                    <i class="fas fa-video-camera"></i>
                </span>
                Video Consultations
            </a>
        </li>
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/appointment/text-consultation-list">
                <span class="icon">
                    <i class="fas fa-comments"></i>
                </span>
                Text Consultations
            </a>
        </li>
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/appointment/clinic-consultation-list">
                <span class="icon">
                    <i class="fas fa-comments"></i>
                </span>
                Clinic Consultations
            </a>
        </li>
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/appointment/consultancy-note-list">
                <span class="icon">
                    <i class="fas fa-stethoscope"></i>
                </span>
                Consultation Notes
            </a>
        </li>					                  
        <li class="">
            <!-- an example of nested submenu. basic bootstrap collapse component -->
            <a href="<?php echo HOSTPATH; ?>doctor/prescription/index">
                <span class="icon">
                    <i class="fas fa-prescription"></i>
                </span>
                Prescription
            </a>
        </li>					                  

        <!--<li class="">
           
            <a href="monitoring.php">
                <span class="icon">
                    <i class="fas fa-desktop"></i>
                </span>
                Monitoring
            </a>

        </li>

        <li class="">
           
            <a href="">
                <span class="icon">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>

                </span>
                Reports
            </a>

        </li>

        <li class="">
           
            <a href="">
                <span class="icon">
                    <i class="fa fa-book" aria-hidden="true"></i>

                </span>
                Blog
            </a>

        </li>

        <li class="">
            
            <a href="">
                <span class="icon">
                    <i class="fa fa-cogs" aria-hidden="true"></i>

                </span>
                Settings
            </a>

        </li>

        <li class="">
            
            <a href="">
                <span class="icon">
                    <i class="fa fa-question-circle" aria-hidden="true"></i>

                </span>
                Help
            </a>

        </li>-->


    </ul>
</div>


