<nav class="navbar navbar-expand-lg navbar-light bb-light" style=" background-color: #E84848;height:3.8rem">
 
  <h4 style="font-weight:500;color:#fff"><b>Patient Listing</b></h4>
  <button style="float:right;background-color:#FFF;border-radius:5%;margin-left:45rem;border:1px solid green;color:green"><a href = "<?php echo WWW_ROOT; ?>patients/register">+New Patient</a></button>
  
</nav>
<div class="sidenav">
	<nav class="navbar navbar-expand-lg navbar-light bb-light" style="background-color: #E84848;height:3.8rem;border-bottom: 1px solid #fff; color:#fff">
		<a class="navbar-brand" href="#">
		<img src="images/logo.png" style="border-radius:50%"; width="50" height="50" alt="">
	    </a><h5 style="font-weight:600">MEDRECHAINCODE</h5>
	</nav>
	</div>