<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <section class="widget">
		 <div class="widget-body">
			
			<div>
			https://www.google.com/maps/place/Popular+Hospital/@12.9746702,77.5583139,12z/data=!4m8!1m2!2m1!1sbangulure+hospitals!3m4!1s0x0:0x6b54a5bb06a7eba5!8m2!3d12.9519075!4d77.5703001</div>
			</div>
       </section>
       </main>
</div>
    </div>

<script language="javascript">


</script>

