	<div class="container-fluid">
        <div class="content-wrap">	
			
		<main id="content" class="content" role="main">
		<div class="row">
			<div class="col-lg-11">
				<div class="well">
				<section class="widget">
					<div class="row">
						<div class="col-sm-9">
								<h4 class="page-title">Health Profile </h4>
								<h6>
								<a href="#">
								<span class="fw-semi-bold">Health Profile >></a></span>View Health Profile</h6>
							</div>
						<div class="col-sm-3">
							
					<ul class="">
						<b>
						 <a href="index.php">
                            <span class="icon">
                                <i class="fa fa-cogs"></i>
                            </span>
                            Settings
                        </a>&nbsp;
						
						 <a href="index.php">
                            <span class="icon">
                                <i class="fa fa-question-circle"></i>
                            </span>
                            Help
						 </a>
						 </b>	
						</ul>
				</div>
				</div>
				</section>
				</div>
				</div>
				</div>
			<div class="row">
			<div class="col-lg-11">
				<div class="well">
				<section class="widget">
				<form class="form-horizontal" role="form">
                        <fieldset>
                                <div class="form-group row">
                                    <label for="normal-field" class="col-md-3 form-control-label text-md-right">Health Condition</label>
                                    <div class="col-md-7">
                                        <select data-placeholder="Form of Medicine" name="form_of_medicine"  data-width="auto" data-minimum-results-for-search="10" tabindex="-1" class="select2 form-control select2-hidden-accessible" id="default-select" aria-hidden="true">
                                            <option value="" selected="selected"></option>
                                            <option value="Tablet">current</option>
											<option value="Tablet">previous</option>
                                           
                                        
                                        </select>
                                    </div>
                                </div>
								<div class="form-group row">
                                    <label for="normal-field" class="col-md-3 form-control-label text-md-right">Diagnosed in</label>
                                    <div class="col-md-7">
                                        <input type="text" id="diagnosed" class="form-control" placeholder="" name = 'diagnosed'>
                                    </div>
                                </div>
								<div class="form-group row">
                                    <label for="normal-field" class="col-md-3 form-control-label text-md-right">Medications</label>
                                    <div class="col-md-7">
                                        <input type="text" id="Medications" class="form-control" placeholder="Medications Name" name = 'Medications'>
                                    </div>
                                </div>
								<div class="form-group row">
                                    <label for="normal-field" class="col-md-3 form-control-label text-md-right">Treated By</label>
                                    <div class="col-md-7">
                                        <input type="text" id="treated" class="form-control" placeholder="Doctor name" name = 'treated by'>
                                    </div>
                                </div>	
								<div class="form-group row">
                                    <label for="normal-field" class="col-md-3 form-control-label text-md-right">Notes</label>
                                    <div class="col-md-7">
                                        <textarea rows="4" class="form-control" name="text" id="o_instruction"></textarea>
                                    </div>
                                </div>	
                            </fieldset>
							 <div class="form-actions">
                                <div class="row">
                                    <div class="offset-md-4 col-md-7 col-12">
                                        <button type="submit" class="btn btn-primary" value="submit">Save</button>
                                        <button type="button" class="btn btn-inverse">Cancel</button>
                                    </div>
                                </div>
                            </div>

                             
				</form>	
				</section>
				</div>
			</div>
			</div>
				
				</main>
			  </div>
				</div>