<div class="container-fluid">
        <div class="content-wrap">
    <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
    <main id="content" class="content" role="main">
        <section class="widget">
		 <div class="widget-body">
			
			<div>
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d60536.10053696839!2d73.83568822508208!3d18.506009723024977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1spune%20hospital!5e0!3m2!1sen!2sin!4v1572610658160!5m2!1sen!2sin" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
			</div>
       </section>
       </main>
</div>
    </div>

<script language="javascript">


</script>

