<div class="container-fluid">
    <div class="content-wrap">	
        <main id="content" class="content" role="main">

            <div class="row">
                <div class="col-lg-12">
                    <div class="well">
                        <section class="widget" style="background-color:#FFF; margin-top:2rem">
                            <?php if(!empty($this->formdata['id'])){ ?>
                                <form style="padding:15px" name = "frmPatentRegister" id = "frmPatentRegister" method="POST" action ="<?php  echo  $this->url(array('action' => 'save-patient-profile'), 'hospitalPatient', true) ?>">
                            
                            <?php }else{ ?>
                                
                                <form style="padding:15px" name = "frmPatentRegister" id = "frmPatentRegister" method="POST" action ="<?php echo  $this->url(array('action' => 'register'), 'hospitalPatient', true) ?>">
                            
                            <?php }?>
                                <input type="hidden" id="example-date-input-id" name = "id" value = "<?php echo $this->formdata['id'];?>">
                                        
                                <div class="form-group row" style ="text-align: center;">
                                    
                                    <div class="col-md-11">
                                        
                                        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
            <div class="notification-error">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
        <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
            <div class="notification-suc">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
                                     
                                        
                                    </div>
                                </div>
                        
                                    
                                    
             
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">TPA Name</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Surgeon">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">TPA Code</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Assistant">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Aneshthesist">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Phone</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Staff">
    </div>
  </div>

<div class="form-group col-md-6">
      <label for="inputPassword4">Contact Person Name</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Type">
    </div>
  
  <div class="form-group col-md-6">
      <label for="inputPassword4">Contact Person Phone</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Part">
    </div>
  

  <div class="form-group">
  <label for="exampleFormControlTextarea2">Address</label>
  <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="2"></textarea>
</div>



<br>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Code</th>
      <th scope="col">Phone</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
      <td><button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="
glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
</button>
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="
glyphicon glyphicon-edit" aria-hidden="true"></span>
</button>
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="
glyphicon glyphicon-trash" aria-hidden="true"></span>
</button>
</td>
    </tr>
    
  </tbody>
</table>
  
                               
                                
                               
                                <hr>
                               

                                
                                <button type="button" style="text-align:right" class="btn btn-danger">Cancel</button>

                                <button type="submit" style="text-align:right" class="btn btn-success" name = "add">Save</button>

                            </form>
                        </section>
                    </div>
                </div>
            </div>

        </main>
    </div>	
</div>

<script>
    function cancel(url) {
        window.location = url;
    }
    
    

//$("#example-date-input-dob").datepicker("setDate", '01/01/2020');


//$('.datepicker').pickadate({ min: new Date(2015,3,20),
//max: new Date(2015,7,14)
//})


</script>

<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
<script>
	 $(document).ready(function(){
      var i=1;
     $("#add_row").click(function(){
      $('#addr'+i).html("<td>"+ (i+1) +"</td><td><input name='name"+i+"' type='text' placeholder='Name' class='form-control input-md'  /> </td><td><input  name='mail"+i+"' type='text' placeholder='Quantity'  class='form-control input-md'></td>  class='form-control input-md'></td>");

      $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
      i++; 
  });
     $("#delete_row").click(function(){
    	 if(i>1){
		 $("#addr"+(i-1)).html('');
		 i--;
		 }
	 });

});
	</script>
