<div class="container-fluid">
    <div class="content-wrap">	
        <main id="content" class="content" role="main">

            <div class="row">
                <div class="col-lg-12">
                    <div class="well">
                        <section class="widget" style="background-color:#FFF; margin-top:2rem">
                            <?php if (!empty($this->formdata['id'])) { ?>
                                <form style="padding:15px" name = "frmPatentRegister" id = "frmPatentRegister" method="POST" action ="<?php echo $this->url(array('action' => 'saveappoinment'), 'hospitalAppointment', true) ?>">

                                <?php } else { ?>

                                    <form style="padding:15px" name = "frmPatentRegister" id = "frmPatentRegister" method="POST" action ="<?php echo $this->url(array('action' => 'saveappoinment'), 'hospitalAppointment', true) ?>">

                                    <?php } ?>



                                    <input type="hidden" id="example-date-input-id" name = "id" value = "<?php echo $this->id; ?>">
                                    <input type="hidden" id="example-date-input-id" name = "rid" value = "<?php echo $this->rid; ?>">
                                    <input type="hidden" id="a_id" name = "a_id" value = "<?php echo $this->formdata['a_id']; ?>">

                                    <div class="form-group row" style ="text-align: center;">
                                        



                                        <div class="col-md-11">

                                            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                                            <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
                                                <div class="notification-error">
                                                    <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                        <?php echo $msg; ?>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>
                                            <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
                                                <div class="notification-suc">
                                                    <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                        <?php echo $msg; ?>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>


                                        </div>
                                    </div>

                                  <div class="row">

                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    Registration Date: <?php echo $this->registration_date;?>
                                                </div>
                                            </div>

                                            
                                            

                                        </div>

                                    
                                    
                                                                            <div class="row">

                                           

                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    Previous Appointment Date: <?php echo $this->last_appnt_date;?>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    Previous Paid Appointment Date: <?php echo $this->prevoiusPaidAppointmentDate;?>
                                                </div>
                                            </div>
                                            

                                        </div>
                                    
                                    <div class="row">

                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <input class="patient-type" type="radio" id="opd" name = "apnt_patient_type" value = "1" checked=""> OPD
                                            </div>
                                            <div class="form-group">
                                                <!--<input class="form" type="radio" id="ipd" name = "apnt_patient_type" value = "2"> IPD-->
                                            </div>
                                        </div>


                                    </div>


                                    <div class="row">

                                        <div class="col-sm-6">
                                            
                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Registration No</b></label>
                                                <input class="form-control" type="text" id="example-date-input-referred_by" value = "<?php echo $this->rid; ?>" disabled="">
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Date Of Appointment</b></label>
                                                <input class="form-control" type="date" id="example-date-input-doa" name = "doa" value = "<?php echo $this->formdata['date_of_admission']; ?>">
                                            </div>


                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Specialization</b></label>
                                                <select class="custom-select" name ="specialization" id ="specialization" onChange = "javascript:changeDoctor(this.value);">
                                                    <option value="">Please select</option>
                                                    <?php
                                                    if (!empty($this->spcData)) {
                                                        //$this->formdata['doctor_id'];
                                                        $selected = '';
                                                        foreach ($this->spcData as $val) {
                                                            if ((isset($this->formdata['specialization_id'])) && ($this->formdata['specialization_id'] == $val['id'])) {
                                                                $selected = "selected = selected";
                                                            } else {
                                                                $selected = '';
                                                            }
                                                            ?>

                                                            <option value="<?php echo $val['id']; ?>" <?php echo $selected; ?>><?php echo $val['name']; ?></option>

                                                        <?php
                                                        }
                                                    }
                                                    ?>

                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Doctor</b></label>
                                                <select class="custom-select" name ="doctor" id ="doctor">
                                                    <option value="">Please select</option>
                                                    <?php
                                                    if (!empty($this->doctorData)) {
                                                        $selected = '';
                                                        foreach ($this->doctorData as $val) {
                                                            if ($this->formdata['doctor_id'] == $val['id']) {
                                                                $selected = "selected = selected";
                                                            } else {
                                                                $selected = '';
                                                            }
                                                            ?>

                                                            <option value="<?php echo $val['id']; ?>"<?php echo $selected; ?>><?php echo $val['name']; ?></option>

                                                        <?php
                                                        }
                                                    }
                                                    ?>


                                                </select>
                                            </div>





                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Referred By</b></label>
                                                <input class="form-control" type="text" id="example-date-input-referred_by" name = "referred_by" value = "<?php echo $this->formdata['referred_by']; ?>">
                                            </div>



                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Relation</b></label>
                                                <select class="custom-select" name ="relation" id ="relation">
                                                    <option value="">Please Select</option>

                                                    <?php
                                                    $selected = '';

                                                    foreach ($this->arrRelation as $key => $relation) {

                                                        if ($this->formdata['relation'] == $key) {
                                                            $selected = "selected = selected";
                                                        } else {
                                                            $selected = '';
                                                        }
                                                        ?>

                                                        <option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $relation; ?></option>
<?php } ?>


                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1"><b>Relative Name/Gourdian</b></label>
                                                <input class="form-control" type="text" id="example-date-input-relative_name" name = "relative_name" value = "<?php echo $this->formdata['relative_name']; ?>">
                                            </div>

                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row"></div>
                                    <button type="button" style="text-align:right" class="btn btn-danger">Cancel</button>

                                    <button type="submit" style="text-align:right" class="btn btn-success" name = "add">Save</button>

                                </form>
                        </section>
                    </div>
                </div>
            </div>

        </main>
    </div>	
</div>

<script>
    function cancel(url) {
        window.location = url;
    }


    $('input[name=apnt_patient_type]').change(function () {


        if ($(this).val() === '1') {
            window.location = window.location.href = hospitalPath + "appointment/patient-appointment-addedit" + "/id/<?php echo $this->id; ?>/rid/<?php echo $this->rid; ?>";
        } else if ($(this).val() === '2') {
            window.location = window.location.href = hospitalPath + "appointment/patient-appointment-ipd-addedit" + "/id/<?php echo $this->id; ?>/rid/<?php echo $this->rid; ?>";
        }



    });


</script>
