<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/jquery-ui.min.css">
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/ui.jqgrid.min.css">
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/ui.jqgrid.css"/>
<link rel="stylesheet" href="<?php echo WEBSITE_URL; ?>css/jqgrid/qunit-2.6.2.css">

 <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="style.css">


<script src="<?php echo WEBSITE_URL; ?>js/jqgrid/jquery.jqgrid.min.js"></script>
<div class="container-fluid">
    <div class="content-wrap">		
        <main id="content" class="content" role="main">
            <div class="row">
                <div class="col-lg-11">
                    <div class="well">
                        <section class="widget">
                            <div class="row">


                                <div class="col-sm-5">
                                    <h4 class="page-title">Your Doctor Experience </h4>
                                    <h6>
                                      <div class="rate">
										<input type="radio" id="star5" name="rate" value="5" />
										<label for="star5" title="text">5 stars</label>
										<input type="radio" id="star4" name="rate" value="4" />
										<label for="star4" title="text">4 stars</label>
										<input type="radio" id="star3" name="rate" value="3" />
										<label for="star3" title="text">3 stars</label>
										<input type="radio" id="star2" name="rate" value="2" />
										<label for="star2" title="text">2 stars</label>
										<input type="radio" id="star1" name="rate" value="1" />
										<label for="star1" title="text">1 star</label>
									  </div>
									  </div>
                                <div class="col-sm-7">



                                    <!--<ul class="">

           

                                        <b>
                                            <a href="<?php echo HOSTPATH; ?>doctor/appointment/clinic-consultation-addedit">
                                                <span class="icon">
                                                    <i class="fa fa-hospital-o"></i>
                                                </span>
                                                Clinic consultation
                                            </a>

                                            <a href="<?php echo HOSTPATH; ?>doctor/appointment/video-consultation-addedit">
                                                <span class="icon">
                                                    <i class="fa fa-video-camera"></i>
                                                </span>
                                                Video Consultation
                                            </a>

                                            <a href="index.php">
                                                <span class="icon">
                                                    <i class="fa fa-cogs"></i>
                                                </span>
                                                Settings
                                            </a>

                                            <a href="index.php">
                                                <span class="icon">
                                                    <i class="fa fa-question-circle"></i>
                                                </span>
                                                Help
                                            </a>

                                        </b>	
                                    </ul>-->

                                </div>

                            </div>
                        </section>
                    </div>
                </div>
            </div>



            
           		   
</main>
</div>
<style>
*{
    margin: 0;
    padding: 0;
}
.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}
</style>