<div class="container-fluid">
    <div class="content-wrap">
        <!-- main page content. the place to put widgets in. usually consists of .row > .col-lg-* > .widget.  -->
        <main id="content" class="content" role="main">
            <!-- Page content -->
            <!-- <ol class="breadcrumb">
                 <li class="breadcrumb-item">Dashboard</li>
                 <li class="breadcrumb-item active">Patient profile</li>
             </ol>-->

            <div class="row" style="margin-left:25px;">
                <div class="col-md-form" style="max-width: 90%;">
                    <section class="widget">

                        <div class="widget-body">
                            <form class="form-horizontal" action="<?php echo $this->url(array('action' => 'saveinvetigation'), '', true); ?>" method="POST">
                                <input type = "hidden" id ="patient_id" name ="patient_id" value = "<?php echo $this->patient_id; ?>">
                                <input type = "hidden" id ="appnt_id" name ="appnt_id" value = "<?php echo $this->appntId; ?>">
                                <input type = "hidden" id ="id" name ="id" value = "<?php echo $this->id; ?>">
                                <input type = "hidden" id ="action_name" name ="action_name" value = "clinic-consultation-addedit">

                                <fieldset>
                                    <legend><strong>Doctor Prescribe</strong> form</legend>
                                    <div class="form-group row" style ="text-align: center;">

                                        <div class="col-md-11">

                                            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                                            <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
                                                <div class="notification-error">
                                                    <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                        <?php echo $msg; ?>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>
                                            <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                                            <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
                                                <div class="notification-suc">
                                                    <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                                                        <?php echo $msg; ?>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>


                                        </div>
                                    </div>
                                    <p>

                                    <div class="form-group row" style="max-width:90%;">

                                        <div><input type="button" id="addRow" value="Patient Vital" onclick="addTableRow();" /></div>


                                        <div id="cont"></div>
                                    </div>                             

                                    <label  for="Consultation">Consultation Notes:</label>

                                    <textarea id="Consultation" rows="4" cols="75">

                                    </textarea>
                                    <p>

                                        <label  for="Doctor">Doctor Pres. Notes:</label>
                                        <textarea id="Dcotornotes" rows="4" cols="75">

                                        </textarea>
                                    <p>
                                        <label  for="Laboratary">Laboretery Test Note:</label>
                                        <textarea id="Laboratery" rows="2" cols="75">

                                        </textarea>
                                    <p>
                                        <label  for="Laboratary">Medicine Advices:</label>
                                    <p>
                                        <label  for="IPD">IPD/Dressing Notes:</label>
                                        <textarea id="Dressing" rows="4" cols="75">

                                        </textarea>
                                    <p>
                                        <label  for="X-rary">X-Ray/ECG/USG:</label>
                                        <textarea id="X-ray" rows="2" cols="75">

                                        </textarea>
                                    <p>
                                        <label  for="IPD">Remarks Notes:</label>
                                        <textarea id="Remark" rows="4" cols="75">

                                        </textarea>
                                    <p>

<!--                                        <input type="button" id="save" value="Submit"/> -->

                                </fieldset>
                                <div class="form-actions">
                                    <div class="row">
                                        <div class="offset-md-4 col-md-7 col-12">
                                            <span id = "sve_btn"><button type="submit" class="btn btn-primary" id = 'button'>Save</button></span>
                                            <button type="button" class="btn btn-inverse" id = "search" onClick = "javascript:cancel('appointment/index');">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div id = "f-l-name"></div>
                        </div>
                    </section>
                </div>

            </div>
        </main>
    </div>
</div>
<script language="javascript">

    function cancel() {
        window.location = doctorPath + 'appointment/index';
    }
    $(document).ready(function () {
        createTable();
    });
</script>
<style>
    table {
        width: 30%;
        font: 17px Calibri;
    }
    table, th, td {
        border: solid 1px #DDD;
        border-collapse: collapse;
        padding: 2px 3px;
        text-align: center;
    }
    .inp-width{
        width:87px;
    }
    th {
        width:87px;
    }

</style>

<script>
    // ARRAY FOR HEADER.
    var arrHead = new Array();
    arrHead = ['', 'ID', 'Blood-Pressure', 'Sugar', 'Heart-Beat', 'BMI', 'Temprature', 'Created-Date', 'Pulse', 'SPO2'];      // SIMPLY ADD OR REMOVE VALUES IN THE ARRAY FOR TABLE HEADERS.

    // FIRST CREATE A TABLE STRUCTURE BY ADDING A FEW HEADERS AND
    // ADD THE TABLE TO YOUR WEB PAGE.
    function createTable() {
        var empTable = document.createElement('table');
        empTable.setAttribute('id', 'empTable');            // SET THE TABLE ID.


        var tr = empTable.insertRow(-1);

        for (var h = 0; h < arrHead.length; h++) {
            var th = document.createElement('th');          // TABLE HEADER.

            th.innerHTML = arrHead[h];
            tr.appendChild(th);

        }

        var div = document.getElementById('cont');
        div.appendChild(empTable);    // ADD THE TABLE TO YOUR WEB PAGE.
    }

    // ADD A NEW ROW TO THE TABLE.s
    function addTableRow() {
        var empTab = document.getElementById('empTable');

        var rowCnt = empTab.rows.length;        // GET TABLE ROW COUNT.
        var tr = empTab.insertRow(rowCnt);      // TABLE ROW.
        tr = empTab.insertRow(rowCnt);

        for (var c = 0; c < arrHead.length; c++) {
            var td = document.createElement('td');          // TABLE DEFINITION.
            td = tr.insertCell(c);

            if (c == 0) {           // FIRST COLUMN.
                // ADD A BUTTON.
                var button = document.createElement('input');

                // SET INPUT ATTRIBUTE.
                button.setAttribute('type', 'button');
                button.setAttribute('value', 'Remove');


                // ADD THE BUTTON's 'onclick' EVENT.
                button.setAttribute('onclick', 'removeRow(this)');

                td.appendChild(button);
            }
            else {
                // CREATE AND ADD TEXTBOX IN EACH CELL.
                var ele = document.createElement('input');
                ele.setAttribute('type', 'text');
                ele.setAttribute('value', '');
                ele.setAttribute('style', 'width:87px;');
                td.appendChild(ele);
            }
        }
    }

    // DELETE TABLE ROW.
    function removeRow(oButton) {
        var empTab = document.getElementById('empTable');
        empTab.deleteRow(oButton.parentNode.parentNode.rowIndex);       // BUTTON -> TD -> TR.
    }

    // EXTRACT AND SUBMIT TABLE DATA.
    function submit() {
        var myTab = document.getElementById('empTable');
        var values = new Array();

        // LOOP THROUGH EACH ROW OF THE TABLE.
        for (row = 1; row < myTab.rows.length - 1; row++) {
            for (c = 0; c < myTab.rows[row].cells.length; c++) {   // EACH CELL IN A ROW.

                var element = myTab.rows.item(row).cells[c];
                if (element.childNodes[0].getAttribute('type') == 'text') {
                    values.push("'" + element.childNodes[0].value + "'");
                }
            }
        }

        // SHOW THE RESULT IN THE CONSOLE WINDOW.
        console.log(values);
    }
</script>
