<style>
.error { border:1px solid #d03166 !important; }
</style>

<script type="text/javascript">
$(document).ready(function() { 
    $("#usertype").change(function(){
        if($(this).val() == '2'){
            $(".busname").show();
	} else {
            $(".busname").hide();
	}
    });
    
    $("#sameemail").click(function(){
       if(this.checked == true){
           $("#username").val($("#email").val());
       } else {
           $("#username").val('');
       }
    });
}); 

function chngpassdiv(){
    $("#chngpass").toggle();
    $("#oldpassword").removeClass("error");
    $("#oldpasserror").html('');
    $("#newpassword").val('');
    $("#oldpassword").val('');
    $("#connewpassword").val('');
}

function checkfields(){ 
    var fname = $("#fname").val();
    var newpass = $("#newpassword").val();
    var oldpass = $("#oldpassword").val();
    var email = $("#email").val();
    var conpass = $("#connewpassword").val();
    var pass = $("#password").val();
    var verifypass = $("#conpassword").val();
    var err = 0;
	
    if(fname == ''){
        $("#fname").addClass("error input-short");
        $("#fname").focus();
        err++;
    } else {
        $("#fname").removeClass( "error" );
    }
    if(email == ''){
        $("#email").addClass( "error input-short" );
	$("#email").focus();
	err++;
    } else {
        $("#email").removeClass( "error" );
    }

    var addtypass = "<?php echo $this->formdata['id']?>"+"xxx";
    if(addtypass == 'xxx'){
        if(pass == ''){
            $("#password").addClass( "error input-short" );
            $("#password").focus();
            err++;
	} else if(verifypass != pass){
            $("#conpassword").addClass( "error input-short" );
            $("#conpassword").focus();
            err++; 
        }
        if(pass != ''){
            $("#password").removeClass( "error" );
        } 
        if(pass != '' && verifypass == pass){
            $("#conpassword").removeClass( "error" ); 
        }
    } else {
        if(oldpass != '' && newpass == ''){
            $("#newpassword").addClass( "error input-short" );
            $("#newpassword").focus();
            err++;
	} else {
            $("#newpassword").removeClass( "error" );
        }
        if(oldpass != '' && conpass == ''){
            $("#connewpassword").addClass( "error input-short" );
            $("#connewpassword").focus();
            err++;
	} else {
            $("#connewpassword").removeClass( "error" );
        }
	if($("#oldpasserror").html() != ''){
            $("#oldpassword").addClass( "error input-short" );
            $("#oldpassword").focus();
            err++;
	} else {
            $("#oldpassword").removeClass( "error" );
        }
	if(conpass != newpass){
            $("#connewpassword").addClass( "error input-short" );
            $("#connewpassword").focus();
            err++;
	} else {
            $("#connewpassword").removeClass( "error" );
        }
    }   
		
    if(err > 0){
        return false;
    } else {
        document.importfile.submit();
    }
}

function removeclass(id){
    $("#"+id).removeClass("error");
}

function chkoldpass(oldpass, userid){
    if(oldpass!=''){
        var allval = 'pass='+oldpass+'&user='+userid;
	$.ajax({
            type : 'post',
            url : "<?php echo $this->url(array('action' => 'checkoldpass', 'page'=>'1'), 'adminUser', true) ?>",
            data : allval,
            success : function(data){
                if(data=='no'){
                    $("#oldpassword").addClass( "error input-short" );
                    $("#oldpasserror").html('Check your old password');
                    return false;
		} else {
                    $("#oldpassword").removeClass( "error" );
                    $("#oldpasserror").html('');
		}
            }
	});
    }
}
</script>

<div class="module">
    <h2><span>Add New User</span></h2>
    <div class="module-body">
        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

       <?php if ($flashMessenger->setNamespace('success')->hasMessages()){?>
           <span class="notification-suc n-success">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </span>
       <?php } ?>

       <?php if ($flashMessenger->setNamespace('error')->hasMessages()){ ?>
           <div class="notification-err o-error">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </div>
 <?php } ?>
        <div class="float-right"><input type="button" onClick ="window.location.href = '<?php echo $this->url(array('action' => 'index', 'page' => '1'), 'adminUser', true) ?>'"value="Back" class="submit-gray"></div>
        <form name ="importfile" enctype="multipart/form-data" action="<?php echo $this->url(array('action' => 'addnewuser'), 'adminUser', true) ?>" method="POST">
            <input type="hidden" id="id" name="id" value="<?php echo $this->formdata['id']; ?>" />
            <input type="hidden" id="photo" name="photo" value="<?php echo $this->formdata['photo']; ?>" />
            <p>
                <label>Email<b>*</b></label>
                <input id="email" name="email" type="text" value="<?php echo $this->formdata['email']; ?>" class="input-short">
            </p>
            
            <div style="float:right;">
                <?php if ($this->formdata['photo'] == '') { ?>
                <div id="userimage" style="float:left; border:solid 1px;"><img width="120" height="120" alt="New article" src="<?php echo ADMIN_IMAGE_URL ?>Crystal_Clear_user.GIF" ></div>
                <?php } else if(file_exists(UPLOAD_FILE_PATH.'/images/userimages/main/'.$this->formdata['photo'])){ ?>
		<div id="userimage" style="float:left; border:solid 1px;"><img width="120" height="120" alt="New article" src="<?php echo userImage_main ?>/<?php echo $this->formdata['photo']; ?>" ></div>
                <br/><div style="float:left; margin-left:40px;"><a href="<?php echo $this->url(array('action' => 'deleteuserpic', 'id' => $this->formdata['id']), 'adminUser', true) ?>">Delete</a></div>
		<?php } else { ?>
                <div id="userimage" style="float:left; border:solid 1px;"><img width="120" height="120" alt="New article" src="<?php echo ADMIN_IMAGE_URL ?>Crystal_Clear_user.GIF" ></div>
                <?php } ?>
            </div>
            
            <!--<p>
                <label>Username</label>
                <input id ="username" name ="username" type="text" value="<?php echo $this->formdata['username']; ?>" class="input-short">
                <input type="checkbox" name="sameemail" id="sameemail"> same as email
            </p>-->
            <p>
                <label>First Name<b>*</b></label>
                <input id ="fname" name ="fname" type="text" value="<?php echo $this->formdata['fname']; ?>" class="input-short">
            </p>
            <p>
                <label>Last Name</label>
                <input id ="lname" name="lname" type="text" value="<?php echo $this->formdata['lname']; ?>" class="input-short">

            </p>
            
            <div style="float:right;">
                <input style="width:200px;" class ="input-short" type="file" name="userphoto" id="userphoto"/>
            </div>
            
            <p>
                <label>Password<b>*</b></label>
                <?php if(empty($this->formdata['id'])){ ?>
		<input autocomplete="off" id ="password" name ="password" type="password" value="<?php echo $this->formdata['password']; ?>" class="input-short">
		<?php } else { ?>
		<a href="javascript:void(0);" onclick="chngpassdiv();"><b>Change Password</b></a>
		<?php } ?>
            </p>
            
            <?php if(empty($this->formdata['id'])){ ?>
            <p>
                <label>Confirm Password</label>
                <input autocomplete="off" id ="conpassword" name ="conpassword" type="password" value="" class="input-short">
            </p>
            <?php } ?>
			
            <?php if(!empty($this->formdata['id'])){ ?>
            <p id="chngpass" style="display:none;">
                <label>Old Password</label>
                <input autocomplete="off" id ="oldpassword" name ="oldpassword" type="password" value="" class="input-short" onblur="chkoldpass(this.value, <?= $this->formdata['id']; ?>);"><span id="oldpasserror" style="color:#d03166;padding-left:5px;"></span>

                <label>New Password</label>
                <input autocomplete="off" id ="newpassword" name ="newpassword" type="password" value="" class="input-short">

                <label>Confirm New Password</label>
                <input autocomplete="off" id ="connewpassword" name ="connewpassword" type="password" value="" class="input-short">
            </p>
            <?php } ?>

            <p>
                <label>Role</label>
                <select id ="role" name ="role" class="input-short">
                    <?php foreach($this->allroles as $roleVal){ ?>
                    <option value="<?php echo $roleVal['id']; ?>" <?php if ($this->formdata['role'] == $roleVal['id']) echo 'selected="selected"'; ?>><?php echo $roleVal['name']; ?></option>
                    <?php } ?>
                </select>
            </p>

            <fieldset>
                <input type="button" value="Submit" id="adduser" name="adduser" class="submit-green" onClick ="return checkfields();"> 
                <input type="button" onClick ="window.location.href = '<?php echo $this->url(array('action' => 'index', 'page' => '1'), 'adminUser', true) ?>'"value="Cancel" class="submit-gray">
            </fieldset>

        </form>
    </div> <!-- End .module-body -->
</div>