<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

       <?php if ($flashMessenger->setNamespace('success')->hasMessages()){?>
           <span class="notification-suc n-success">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </span>
       <?php } ?>

       <?php if ($flashMessenger->setNamespace('error')->hasMessages()){ ?>
           <div class="notification-err o-error">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </div>
 <?php } ?>
<div style="float:right">
    <?php if($this->messageSection == 1) {?>
        <a href="/admin/user/msg-email" class="button">
            <span>Send email to user<img height="9" width="12" src="<?php echo ADMIN_IMAGE_URL; ?>Sign-Forward-icon.png" alt="New article"></span>
        </a> 
    <?php }else if($this->messageSection == 2){ ?>
        <a href="/admin/user/msg-mobile" class="button">
        <span>Send message to user<img height="9" width="12" src="<?php echo ADMIN_IMAGE_URL; ?>Sign-Forward-icon.png" alt="New article"></span>
    </a> 
    <?php } ?>
</div>
<div style="clear:both;"></div>

<h2><span></span></h2>
<!-- Example table -->

    <div class="module-table-body">
        <div id="gridWidth" class="left">
                <table id="userList" width="100%" border="0" cellpadding="0" cellspacing="0"></table>
                
        </div>
        
        <div style="clear: both"></div>
    </div> <!-- End .module-table-body -->
<div id="pager2"></div>

     

<script language="javascript">

    
            $.jgrid.no_legacy_api = true;
            $.jgrid.useJSON = true;
            var grid = jQuery("#userList");
            var pages = []; // not as {};
            var emptyMsgDiv = $('<div class="no-record-msz"><?php echo RESULT_NOT_FOUND; ?></div>');
            var messageSection = "<?php echo $this->messageSection; ?>";
            var userTypeStr = "<?php echo USER_TYPE_STR; ?>";
            if(messageSection == 1){
                jQuery("#userList").jqGrid(
                {
                url: adminPath + 'user/all-sent-email-mobile-list/message-section/'+messageSection,
                datatype: "json",
                colNames: [ '<?php echo 'ID'; ?>',
                        '<?php echo 'User type'; ?>',
                        '<?php echo 'User name'; ?>',
                        '<?php echo 'Name'; ?>',
                        '<?php echo 'Email'; ?>',
                        '<?php echo 'Subject'; ?>',
                        '<?php echo 'Date'; ?>'
                ],
                colModel: [
                {name: 'id', index: 'id', width: 50, search: true,sort:true},
                {name: 'user_type', index: 'user_type', width: 100,sortable: false, stype:"select",
                searchoptions: {
                value: userTypeStr,
                defaultValue: ""
                } },        
                {name: 'username', index: 'username', width: 150, search: true,sort:true},    
                {name: 'name', index: 'name', width: 150, search: true,sort:true},
                {name: 'email', index: 'email', width: 150, search: true,sort:true },
                {name: 'email_subject', index: 'email_subject', width: 150, search: true,sort:true },                
                {name: 'created_at', index: 'created_at', width: 150, search: false,sort:true},            
                ],
                rowNum:<?php echo NO_OF_RECORDS_PER_PAGE; ?>,
                mtype: 'post',
                width: jQuery('#gridWidth').width(),
                height: '100%',
                rowList:[<?php echo ROWLIST; ?>],
                pager: '#pager2',
                sortname: 'id',
                sortorder: "DESC",
                caption:"User/Vendor Email List",
                autosearch: true,
                toppager: false,
                viewrecords: true,
                altRows:true,
                altclass:'grid-Alternate-Row',
                rownumbers: true,
                recordtext: "View {0} - {1} of {2}",
                emptyrecords: false,
                /*loadtext: "Loading",*/
                width: 1200,
                multiselect: true, // <------like here or your choice.
               /* hoverrows: false,*/
               editurl: adminPath + 'user/msg-delete/message-section/'+messageSection,
                loadComplete: function() {
                    var count = grid.getGridParam();
                    var ts = grid[0];
                    if (ts.p.reccount === 0) {
                        grid.hide();
                        emptyMsgDiv.show();
                    } else {
                    //$("#gridoperation").show();
                            grid.show();
                            emptyMsgDiv.hide();
                    }
                }/*,
                beforeSelectRow: function(rowid) {
                if ($('jqg_userList_' + rowid).attr("checked") == 'checked')
                        return true;
                        else {
                        $('#' + rowid).removeClass('ui-state-highlight');
                                return false;
                        }
                }*/
        });
    }else if(messageSection == 2){
    
        jQuery("#userList").jqGrid(
            {
            url: adminPath + 'user/all-sent-email-mobile-list/message-section/'+messageSection,
            datatype: "json",
            colNames: [ '<?php echo 'ID'; ?>',
                    '<?php echo 'User type'; ?>',
                    '<?php echo 'User name'; ?>',
                    '<?php echo 'Name'; ?>',                     
                    '<?php echo 'Mobile'; ?>',                       
                    '<?php echo 'Date'; ?>'
            ],
            colModel: [
            {name: 'id', index: 'id', width: 50, search: true,sort:true}, 
            {name: 'user_type', index: 'user_type', width: 100,sortable: false, stype:"select",
                searchoptions: {
                value: userTypeStr,
                defaultValue: ""
                } },
            {name: 'username', index: 'username', width: 150, search: true,sort:true},     
            {name: 'name', index: 'name', width: 150, search: true,sort:true},            
            {name: 'mobile', index: 'mobile', width: 150, search: true,sort:true },            
            {name: 'created_at', index: 'created_at', width: 150, search: false,sort:true},            
            ],
            rowNum:<?php echo NO_OF_RECORDS_PER_PAGE; ?>,
            mtype: 'post',
            width: jQuery('#gridWidth').width(),
            height: '100%',
            rowList:[<?php echo ROWLIST; ?>],
            pager: '#pager2',
            sortname: 'id',
            sortorder: "DESC",
            caption:"User/Vendor Message List",
            autosearch: true,
            toppager: false,
            viewrecords: true,
            altRows:true,
            altclass:'grid-Alternate-Row',
            rownumbers: true,
            recordtext: "View {0} - {1} of {2}",
            emptyrecords: false,
            /*loadtext: "Loading",*/
            width: 1200,
            multiselect: true, // <------like here or your choice.
           /* hoverrows: false,*/
           editurl: adminPath + 'user/msg-delete/message-section/'+messageSection,
            loadComplete: function() {
                var count = grid.getGridParam();
                var ts = grid[0];
                if (ts.p.reccount === 0) {
                    grid.hide();
                    emptyMsgDiv.show();
                } else {
                //$("#gridoperation").show();
                        grid.show();
                        emptyMsgDiv.hide();
                }
            }/*,
            beforeSelectRow: function(rowid) {
            if ($('jqg_userList_' + rowid).attr("checked") == 'checked')
                    return true;
                    else {
                    $('#' + rowid).removeClass('ui-state-highlight');
                            return false;
                    }
            }*/
    });
    
    
    }
    
    
    
            // place div with empty message insde of div
            emptyMsgDiv.insertAfter(grid.parent());
            emptyMsgDiv.hide();
            jQuery("#userList").jqGrid('navGrid', '#pager2', {edit: false, add: false, del: true, search: false});
            
            jQuery('#userList').jqGrid('filterToolbar', {"stringResult": true,searchOnEnter : false});
            myGrid = jQuery("#userList");
           
            var cm = myGrid[0].p.colModel;
            $.each(myGrid[0].grid.headers, function(index, value) {
            var cmi = cm[index], colName = cmi.name;
                    if (!cmi.sortable && colName !== 'rn' && colName !== 'cb' && colName !== 'subgrid') {
            $('div.ui-jqgrid-sortable', value.el).css({cursor: "default"});
            }
            });   
            
            
            $.extend($.fn.fmatter, {
                actionFormatter: function(cellvalue, options, rowObject) {
                    var retVal = "<a onclick='return editUserDetails("+ options.rowId + ");' href='javascript:void(0);'><span class='ui-icon ui-icon-pencil'></span></a>";
                    return retVal;
                }
            });
            
            function editUserDetails(roleId){
                window.location.href = adminPath + 'user/addedit/id/' + roleId;
            }
</script>
