<script src="<?php echo WEBSITE_URL; ?>css/application.min.css"></script>
<div class="container-fluid">
    <div class="content-wrap">	

        <main id="content" class="content" role="main">
            <div class="row">
                <div class="col-lg-11">
                    <div class="well">
                        <section class="widget">
                            <div class="widget-body">
<form class="form-horizontal" action="" method="POST">
<!--                            <input type = "hidden" id ="doctor_id" name ="doctor_id" value = "<?php //echo $this->formdata['doctor_id'];?>">-->
                            
                            <fieldset>
                                <legend><strong>Your Doctors</strong> Experience</legend>
                                
                                
                                <div class="form-group row" style ="text-align: center;">
                                    
                                    <div class="col-md-11">
                                        
                                        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('error')->hasMessages()) { ?>
            <div class="notification-error">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
        <?php //$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
        <?php if ($flashMessenger->setNamespace('success')->hasMessages()) { ?>
            <div class="notification-suc">
                <?php foreach ($flashMessenger->getMessages() as $msg) { ?>
                    <?php echo $msg; ?>
                <?php } ?>
            </div>
        <?php } ?>
                                     
                                        
                                    </div>
                                </div>
                                
                                
                                <div class="form-group row">
                                    <label for="normal-field" class="col-md-4 form-control-label text-md-right">Department</label>
                                    <div class="col-md-7">
                                        <select data-placeholder="Department Name" data-width="auto" tabindex="-1" class="select2 form-control select2-hidden-accessible" id="departmentDD" aria-hidden="true" name = "department" onChange = "javascript:changeDoctor(this.value);">
                                            <option value="">Please select</option>
                                            <?php
                                            if (!empty($this->dertData)) {
                                                //$this->formdata['doctor_id'];
                                                $selected = '';
                                                foreach ($this->dertData as $val) {
                                                    if ((isset($this->formdata['department_id'])) && ($this->formdata['department_id'] == $val['id'])) {
                                                        $selected = "selected = selected";
                                                    } else {
                                                        $selected = '';
                                                    }
                                                    ?>

                                                    <option value="<?php echo $val['id']; ?>" <?php echo $selected; ?>><?php echo $val['name']; ?></option>

                                                <?php }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="hint-field" class="col-md-4 control-label text-md-right">
                                        Choose Healthcare Provider
                                        <!--<span class="help-block">Some help text</span>-->
                                    </label>
                                    <div class="col-md-7">
                                        <select name = "doctor" data-placeholder="Doctor Name" data-width="auto" data-minimum-results-for-search="10" tabindex="-1" class="select2 form-control select2-hidden-accessible" id="doctorDD" aria-hidden="true">
                                            <option value="">Please select</option>
                                            <?php
                                            if (!empty($this->doctorData)) {
                                                $selected = '';
                                                foreach ($this->doctorData as $val) {
                                                    if ($this->formdata['healthcare_provider_id'] == $val['id']) {
                                                        $selected = "selected = selected";
                                                    } else {
                                                        $selected = '';
                                                    }
                                                    ?>

                                                    <option value="<?php echo $val['id']; ?>"<?php echo $selected; ?>><?php echo $val['name']; ?></option>

                                                <?php }
                                            }
                                            ?>

                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">

                                    <label for="hint-field" class="col-md-4 control-label text-md-right">
                                        Please Rate Your Doctor

                                    </label>
                                    <div class="col-md-7">
                                        <div class="rate">
                                            <input type="radio" id="star5" name="rating" value="5" />
                                            <label for="star5" title="text">5 stars</label>
                                            <input type="radio" id="star4" name="rating" value="4" />
                                            <label for="star4" title="text">4 stars</label>
                                            <input type="radio" id="star3" name="rating" value="3" />
                                            <label for="star3" title="text">3 stars</label>
                                            <input type="radio" id="star2" name="rating" value="2" />
                                            <label for="star2" title="text">2 stars</label>
                                            <input type="radio" id="star1" name="rating" value="1" />
                                            <label for="star1" title="text">1 star</label>
                                        </div>
                                    </div>
                                </div>
                                <!--                                </div>-->




                                <div class="form-group row">
                                    <label for="hint-field" class="col-md-4 control-label text-md-right">
                                        Please Give Your Valuable Feedback To Improve Our Best
                                         <!--<span class="help-block">Some help text</span>-->
                                    </label>
                                    <div class="col-md-7">
                                        <textarea rows="3" class="form-control" id="note" name = "feedback"></textarea>

                                    </div>
                                </div>

 </fieldset>
                                <div class="form-actions">
                                    <div class="row">
                                        <div class="offset-md-2 col-md-7 col-12">
                                            <button type="button" class="btn btn-inverse">Cancel</button>
                                            <button type="submit" class="btn btn-primary" value="submit">Post</button>
                                        </div>
                                    </div>
                                </div>
                                <!--                                   </div>-->
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </div>


        </main>
    </div>
</div>

