<div class="sidenav" style="margin-top:60px">

    <div class="container">
        <div class="form-group">
                <div class="card-header">
                    Admin
                </div>
        </div>
        <div id="accordion">
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseOne"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Doctor Mgt.
                    </a>
                </div>
                <div id="collapseOne" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>doctor/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Doctor Listing
                        </a>  
                        <a href="<?php echo ADMIN_BASE_URL; ?>doctor/addedit" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Add Doctor
                        </a>
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseNurse"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Nurse Mgt.
                    </a>
                </div>
                <div id="collapseNurse" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>nurse/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Nurse Listing
                        </a>  
                        <a href="<?php echo ADMIN_BASE_URL; ?>nurse/addedit" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Add Nurse
                        </a>
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Laboratory Mgt.
                    </a>
                </div>
                <div id="collapseTwo" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>laboratory/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Laboratory Listing
                        </a>  
                        <a href="<?php echo ADMIN_BASE_URL; ?>laboratory/addedit" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Add Laboratory
                        </a>
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseStaff"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Staff Mgt.
                    </a>
                </div>
                <div id="collapseStaff" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>staff/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Staff Listing
                        </a>  
                        <a href="<?php echo ADMIN_BASE_URL; ?>staff/addedit" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Add Staff
                        </a>
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseThree"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Hospital Mgt.
                    </a>
                </div>
                <div id="collapseThree" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>hospital/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Hospital Listing
                        </a>  
                        <a href="<?php echo ADMIN_BASE_URL; ?>hospital/addedit" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Add Hospital
                        </a>
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#la"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Leave Application.
                    </a>
                </div>
                <div id="la" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>leave-application/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Leave Application
                        </a>  
                        
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#salary"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Salary
                    </a>
                </div>
                <div id="salary" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>salary/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Salary Structure
                        </a>  
                        
                                                      
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#attendence"><i class="fas fa-boxes" aria-hidden="true"></i>
                        Attendence
                    </a>
                </div>
                <div id="attendence" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="<?php echo ADMIN_BASE_URL; ?>attendence/index" id="ember3566" class="category-sub-item nav-link active ember-view">              
                            <span class="octicon octicon-chevron-right">
                            </span>&gt; Attendence List
                        </a>  
                        
                                                      
                    </div>
                </div>
            </div>
            
            
           
           
        </div>
    </div>
</div>