<div class="sidenav" style="margin-top:70px">

    <div class="container">
      
        <div id="accordion">
            
            
            <div class="card">
                <div class="card-header">
                    <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo1">
                        <span class="icon">
                            <i class="fas fa-users" aria-hidden="true"></i>

                        </span>
                        Doctor
                    </a>
                </div>
                <div id="collapseTwo1" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                         <a href="<?php echo DOCTOR_BASE_URL; ?>patient" id="ember1515" class="category-sub-item nav-link active ember-view">          
                            <span class="octicon octicon-chevron-right"></span>&gt; Patients
                        </a> 
                         
                           
                    </div>
                </div>
            </div>
           
            
            
            
           
            
            
            
        </div>
    </div>
</div>