 <!-- common libraries. required for every page-->
<?php 
     $action = $this->actionName;//home
     $controller  = $this->controllerName;//list
    
?>



<script src="<?php echo WEBSITE_URL; ?>js/patient/query.min.js"></script>
<script src="<?php echo WEBSITE_URL; ?>js/patient/responsiveslides.min.js"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL;?>js/new/switchery.js"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL;?>js/new/moment.js"></script>
<script type="text/javascript" src="<?php echo WEBSITE_URL;?>js/new/tempusdominus-bootstrap-4-original.js"></script>
<script src="<?php echo WEBSITE_URL; ?>js/jqgrid/jquery-ui.min.js"></script> 

<script src="<?php echo WEBSITE_URL; ?>js/common.js"></script>
<script>
 $(document).ready(function() {
    
    $('.navbar-nav').click(function() {
        $(".dropdown-menu-right").css("position", "absolute");
        $( ".dropdown-menu-right" ).toggle();
    })
 });
 
 function changeDoctor(dprtId)
    {
        var value = 'dprtId=' + dprtId;
        var select = $("#doctorDD");
        select.empty();
        $.ajax({
            //this is the php file that processes the data
            url: patientPath + 'doctor/getdoctor',
            //GET method is used
            type: 'POST',
            //pass the data			
            data: value,
            //success
            success: function(responseText) {
                $('#doctorDD').append($('<option>').text('Select Doctor').attr('value', ''));
                var obj = jQuery.parseJSON(responseText);
                $.each(obj, function(i, items) {
                    console.log(items['id']);
                    $('#doctorDD').append($('<option>').text(items['name']).attr('value', items['id']));
                });

            }

        });

    }

</script>

