<style>
.error { border:1px solid #d03166 !important; }
</style>
<script type="text/javascript">

function checkfields(){ 
    var name = $("#name").val();    
    var mobile = $("#mobile").val();
    var message = $('#message').val();
    
    var err = 0;
	
    if(name == ''){
        $("#name").addClass("error input-short");
        $("#name").focus();
        err++;
    } else {
        $("#name").removeClass( "error" );
    }
    
    
    if (mobile == '')
     {
        $("#mobile").addClass( "error input-short" );
	$("#mobile").focus();
        err++;
     }else if ((mobile != '') && (isNaN(mobile))){
        $("#mobile").addClass( "error input-short" );
	$("#mobile").focus();
        err++;
    }else if(mobile.length != 10) {
        $("#mobile").addClass( "error input-short" );
	$("#mobile").focus();
        err++;
    }else{
    
        $("#mobile").removeClass( "error" );
    
    }
    
    if(message == ' '){
      
        $("#message").addClass("error input-short");
        $("#message").focus();
        err++;
    } else {
        $("#message").removeClass( "error" );
    }
    
    if(err > 0){           
        return false;
    } else {
        document.sendMobileMsg.submit();
    }
}




</script>

<div class="module">
    <h2><span>Send SMS To User</span></h2>
    <div class="module-body">
        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

       <?php if ($flashMessenger->setNamespace('success')->hasMessages()){?>
           <span class="notification-suc n-success">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </span>
       <?php } ?>

       <?php if ($flashMessenger->setNamespace('error')->hasMessages()){ ?>
           <div class="notification-err o-error">
           <?php foreach ($flashMessenger->getMessages() as $msg){ ?>
               <?php echo $msg; ?>
           <?php } ?>
           </div>
 <?php } ?>
        <div class="float-right"><input type="button" onClick ="window.location.href = '<?php echo $this->url(array('action' => 'all-sent-email-mobile-list', 'message-section' => '2'), 'adminUser', true) ?>'"value="Back" class="submit-gray"></div>
        <form name ="sendMobileMsg" action="<?php echo $this->url(array('action' => 'send-mobile-msg'), 'adminUser', true) ?>" method="POST">
          
            
            
            <input type="hidden" id="id" name="id" value="<?php echo $this->formdata['id']; ?>" />
            
            <p>
                <label>User Type<b>*</b></label>                
                <?php echo $this->formSelect('user_type','',array('id'=>'user_type','class'=>'input-short'),$this->userType);?>
                
            </p>
            
             <p>
                <label>Name<b>*</b></label>
                <?php echo $this->formText('name',$this->formdata['name'],array('id'=>'name','class'=>'input-short'));?>

            </p>
            
            
            <p>
                <label>Mobile<b>*</b></label>
                <?php echo $this->formText('mobile',$this->formdata['mobile'],array('id'=>'mobile','class'=>'input-short'));?>
                
            </p>
            
           
           <p>
                <label>Message<b>*</b></label>

                <?php echo $this->formTextarea('message',$this->formdata['message'],array('id'=>'message'));?>
            </p>
           
            <fieldset>
                <input type="button" value="Submit" id="adduser" name="adduser" class="submit-green" onClick ="return checkfields();"> 
                <input type="button" onClick ="window.location.href = '<?php echo $this->url(array('action' => 'all-sent-email-mobile-list', 'message-section' => '1'), 'adminUser', true) ?>'"value="Cancel" class="submit-gray">
            </fieldset>

        </form>
    </div> <!-- End .module-body -->
</div>